module Pawl.Codec.CounterName where

import qualified Data.Text as Text
import qualified Pawl.JsonCodec.Codec as Codec
import qualified Pawl.JsonCodec.Common as Common
import qualified Pawl.Types.CounterName as CounterName

-- | A bare string on the wire, filed in @$defs@ under its own name, exactly as
-- 'Pawl.Codec.AbilityName' is.
--
-- The rejection lives in the INNER codec rather than in the wrap, because
-- 'Common.wrapper' takes a total injection and so cannot fail.
codec :: Codec.Codec CounterName.CounterName
codec = Common.wrapper unreserved CounterName.UnsafeMkCounterName CounterName.unwrap

-- | 'Common.text' with its decoder tightened to CR 122.1's interchangeability
-- sentence -- a record update, so the encoder and the schema stay shared. A card
-- naming a spelling 'Pawl.Types.CounterKind' already has a constructor for fails
-- to DECODE, so the corpus cannot hold two kinds for one rules object. It goes
-- through 'Pawl.Types.CounterName.make' rather than restating the test, so there
-- is one door and one invariant.
--
-- The schema still says only "string": 'Pawl.Types.CounterName.reserved' is a
-- blocklist rather than a pattern, so the decoder is STRICTER than the schema
-- claims -- the reverse of the governing principle in 'Pawl.JsonCodec.Common',
-- and deliberate. Stating it in the schema means a negative regex with one
-- alternative per reserved spelling, regenerated by hand whenever a kind is
-- added, which is a second copy of the same hand-kept list.
unreserved :: Codec.Codec Text.Text
unreserved =
  Common.text
    { Codec.decode = \value -> CounterName.unwrap <$> (Common.asText value >>= CounterName.make)
    }
