-- Classifications over Pawl.Types.Subtype: which of CR 205.3's disjoint subtype
-- families a subtype belongs to. The rulebook owns these lists outright (CR
-- 205.3i names the land types by name), so casing on a Subtype here is the same
-- kind of act as casing on a Phase -- it is a subtype's IDENTITY, never an
-- effect's.
module Pawl.Engine.Subtype where

import qualified Pawl.Types.Subtype as Subtype

-- | CR 205.3i
isLandType :: Subtype.Subtype -> Bool
isLandType subtype = case subtype of
  Subtype.Cave -> True
  Subtype.Desert -> True
  Subtype.Forest -> True
  Subtype.Gate -> True
  Subtype.Island -> True
  Subtype.Lair -> True
  Subtype.Locus -> True
  Subtype.Mine -> True
  Subtype.Mountain -> True
  Subtype.Plains -> True
  Subtype.Planet -> True
  Subtype.PowerPlant -> True
  Subtype.Sphere -> True
  Subtype.Swamp -> True
  Subtype.Tower -> True
  Subtype.Town -> True
  Subtype.Urzas -> True
  _ -> False

-- | CR 205.3m
isCreatureType :: Subtype.Subtype -> Bool
isCreatureType subtype = case subtype of
  Subtype.Advisor -> True
  Subtype.Aetherborn -> True
  Subtype.Alien -> True
  Subtype.Ally -> True
  Subtype.Angel -> True
  Subtype.Antelope -> True
  Subtype.Ape -> True
  Subtype.Archer -> True
  Subtype.Archon -> True
  Subtype.Armadillo -> True
  Subtype.Army -> True
  Subtype.Artificer -> True
  Subtype.Assassin -> True
  Subtype.AssemblyWorker -> True
  Subtype.Astartes -> True
  Subtype.Atog -> True
  Subtype.Aurochs -> True
  Subtype.Avatar -> True
  Subtype.Azra -> True
  Subtype.Badger -> True
  Subtype.Balloon -> True
  Subtype.Barbarian -> True
  Subtype.Bard -> True
  Subtype.Basilisk -> True
  Subtype.Bat -> True
  Subtype.Bear -> True
  Subtype.Beast -> True
  Subtype.Beaver -> True
  Subtype.Beeble -> True
  Subtype.Beholder -> True
  Subtype.Berserker -> True
  Subtype.Bird -> True
  Subtype.Bison -> True
  Subtype.Blinkmoth -> True
  Subtype.Boar -> True
  Subtype.Bringer -> True
  Subtype.Brushwagg -> True
  Subtype.Camarid -> True
  Subtype.Camel -> True
  Subtype.Capybara -> True
  Subtype.Caribou -> True
  Subtype.Carrier -> True
  Subtype.Cat -> True
  Subtype.Centaur -> True
  Subtype.Child -> True
  Subtype.Chimera -> True
  Subtype.Citizen -> True
  Subtype.Cleric -> True
  Subtype.Clown -> True
  Subtype.Cockatrice -> True
  Subtype.Construct -> True
  Subtype.Coward -> True
  Subtype.Coyote -> True
  Subtype.Crab -> True
  Subtype.Crocodile -> True
  Subtype.Ctan -> True
  Subtype.Custodes -> True
  Subtype.Cyberman -> True
  Subtype.Cyclops -> True
  Subtype.Dalek -> True
  Subtype.Dauthi -> True
  Subtype.Demigod -> True
  Subtype.Demon -> True
  Subtype.Deserter -> True
  Subtype.Detective -> True
  Subtype.Devil -> True
  Subtype.Dinosaur -> True
  Subtype.Djinn -> True
  Subtype.Doctor -> True
  Subtype.Dog -> True
  Subtype.Dragon -> True
  Subtype.Drake -> True
  Subtype.Dreadnought -> True
  Subtype.Drix -> True
  Subtype.Drone -> True
  Subtype.Druid -> True
  Subtype.Dryad -> True
  Subtype.Dwarf -> True
  Subtype.Echidna -> True
  Subtype.Efreet -> True
  Subtype.Egg -> True
  Subtype.Elder -> True
  Subtype.Eldrazi -> True
  Subtype.Elemental -> True
  Subtype.Elephant -> True
  Subtype.Elf -> True
  Subtype.Elk -> True
  Subtype.Employee -> True
  Subtype.Eternal -> True
  Subtype.Eye -> True
  Subtype.Faerie -> True
  Subtype.Ferret -> True
  Subtype.Fish -> True
  Subtype.Flagbearer -> True
  Subtype.Fox -> True
  Subtype.Fractal -> True
  Subtype.Frog -> True
  Subtype.Fungus -> True
  Subtype.Gamer -> True
  Subtype.Gamma -> True
  Subtype.Gargoyle -> True
  Subtype.Germ -> True
  Subtype.Giant -> True
  Subtype.Giraffe -> True
  Subtype.Gith -> True
  Subtype.Glimmer -> True
  Subtype.Gnoll -> True
  Subtype.Gnome -> True
  Subtype.Goat -> True
  Subtype.Goblin -> True
  Subtype.God -> True
  Subtype.Golem -> True
  Subtype.Gorgon -> True
  Subtype.Graveborn -> True
  Subtype.Gremlin -> True
  Subtype.Griffin -> True
  Subtype.Guest -> True
  Subtype.Hag -> True
  Subtype.Halfling -> True
  Subtype.Hamster -> True
  Subtype.Harpy -> True
  Subtype.Hedgehog -> True
  Subtype.Hellion -> True
  Subtype.Hero -> True
  Subtype.Hippo -> True
  Subtype.Hippogriff -> True
  Subtype.Homarid -> True
  Subtype.Homunculus -> True
  Subtype.Horror -> True
  Subtype.Horse -> True
  Subtype.Human -> True
  Subtype.Hydra -> True
  Subtype.Hyena -> True
  Subtype.Illusion -> True
  Subtype.Imp -> True
  Subtype.Incarnation -> True
  Subtype.Inhuman -> True
  Subtype.Inkling -> True
  Subtype.Inquisitor -> True
  Subtype.Insect -> True
  Subtype.Jackal -> True
  Subtype.Jellyfish -> True
  Subtype.Juggernaut -> True
  Subtype.Kangaroo -> True
  Subtype.Kavu -> True
  Subtype.Kirin -> True
  Subtype.Kithkin -> True
  Subtype.Knight -> True
  Subtype.Kobold -> True
  Subtype.Kor -> True
  Subtype.Kraken -> True
  Subtype.Kree -> True
  Subtype.Llama -> True
  Subtype.Lamia -> True
  Subtype.Lammasu -> True
  Subtype.Leech -> True
  Subtype.Lemur -> True
  Subtype.Leviathan -> True
  Subtype.Lhurgoyf -> True
  Subtype.Licid -> True
  Subtype.Lizard -> True
  Subtype.Lobster -> True
  Subtype.Manticore -> True
  Subtype.Masticore -> True
  Subtype.Mercenary -> True
  Subtype.Merfolk -> True
  Subtype.Metathran -> True
  Subtype.Minion -> True
  Subtype.Minotaur -> True
  Subtype.Mite -> True
  Subtype.Mole -> True
  Subtype.Monger -> True
  Subtype.Mongoose -> True
  Subtype.Monk -> True
  Subtype.Monkey -> True
  Subtype.Moogle -> True
  Subtype.Moonfolk -> True
  Subtype.Mount -> True
  Subtype.Mouse -> True
  Subtype.Mutant -> True
  Subtype.Myr -> True
  Subtype.Mystic -> True
  Subtype.Nautilus -> True
  Subtype.Necron -> True
  Subtype.Nephilim -> True
  Subtype.Nightmare -> True
  Subtype.Nightstalker -> True
  Subtype.Ninja -> True
  Subtype.Noble -> True
  Subtype.Noggle -> True
  Subtype.Nomad -> True
  Subtype.Nymph -> True
  Subtype.Octopus -> True
  Subtype.Ogre -> True
  Subtype.Ooze -> True
  Subtype.Orb -> True
  Subtype.Orc -> True
  Subtype.Orgg -> True
  Subtype.Otter -> True
  Subtype.Ouphe -> True
  Subtype.Ox -> True
  Subtype.Oyster -> True
  Subtype.Pangolin -> True
  Subtype.Peasant -> True
  Subtype.Pegasus -> True
  Subtype.Pentavite -> True
  Subtype.Performer -> True
  Subtype.Pest -> True
  Subtype.Phelddagrif -> True
  Subtype.Phoenix -> True
  Subtype.Phyrexian -> True
  Subtype.Pilot -> True
  Subtype.Pincher -> True
  Subtype.Pirate -> True
  Subtype.Plant -> True
  Subtype.Platypus -> True
  Subtype.Porcupine -> True
  Subtype.Possum -> True
  Subtype.Praetor -> True
  Subtype.Primarch -> True
  Subtype.Prism -> True
  Subtype.Processor -> True
  Subtype.Qu -> True
  Subtype.Rabbit -> True
  Subtype.Raccoon -> True
  Subtype.Ranger -> True
  Subtype.Rat -> True
  Subtype.Rebel -> True
  Subtype.Reflection -> True
  Subtype.Rhino -> True
  Subtype.Rigger -> True
  Subtype.Robot -> True
  Subtype.Rogue -> True
  Subtype.Sable -> True
  Subtype.Salamander -> True
  Subtype.Samurai -> True
  Subtype.Sand -> True
  Subtype.Saproling -> True
  Subtype.Satyr -> True
  Subtype.Scarecrow -> True
  Subtype.Scientist -> True
  Subtype.Scion -> True
  Subtype.Scorpion -> True
  Subtype.Scout -> True
  Subtype.Sculpture -> True
  Subtype.Seal -> True
  Subtype.Serf -> True
  Subtype.Serpent -> True
  Subtype.Servo -> True
  Subtype.Shade -> True
  Subtype.Shaman -> True
  Subtype.Shapeshifter -> True
  Subtype.Shark -> True
  Subtype.Sheep -> True
  Subtype.Shiar -> True
  Subtype.Siren -> True
  Subtype.Skeleton -> True
  Subtype.Skrull -> True
  Subtype.Skunk -> True
  Subtype.Slith -> True
  Subtype.Sliver -> True
  Subtype.Sloth -> True
  Subtype.Slug -> True
  Subtype.Snail -> True
  Subtype.Snake -> True
  Subtype.Soldier -> True
  Subtype.Soltari -> True
  Subtype.Sorcerer -> True
  Subtype.Spawn -> True
  Subtype.Specter -> True
  Subtype.Spellshaper -> True
  Subtype.Sphinx -> True
  Subtype.Spider -> True
  Subtype.Spike -> True
  Subtype.Spirit -> True
  Subtype.Splinter -> True
  Subtype.Sponge -> True
  Subtype.Spy -> True
  Subtype.Squid -> True
  Subtype.Squirrel -> True
  Subtype.Starfish -> True
  Subtype.Surrakar -> True
  Subtype.Survivor -> True
  Subtype.Symbiote -> True
  Subtype.Synth -> True
  Subtype.Tentacle -> True
  Subtype.Tetravite -> True
  Subtype.Thalakos -> True
  Subtype.Thopter -> True
  Subtype.Thrull -> True
  Subtype.Tiefling -> True
  Subtype.TimeLord -> True
  Subtype.Toy -> True
  Subtype.Treefolk -> True
  Subtype.Trilobite -> True
  Subtype.Triskelavite -> True
  Subtype.Troll -> True
  Subtype.Turtle -> True
  Subtype.Tyranid -> True
  Subtype.Unicorn -> True
  Subtype.Utrom -> True
  Subtype.Vampire -> True
  Subtype.Varmint -> True
  Subtype.Vedalken -> True
  Subtype.Villain -> True
  Subtype.Volver -> True
  Subtype.Wall -> True
  Subtype.Walrus -> True
  Subtype.Warlock -> True
  Subtype.Warrior -> True
  Subtype.Weasel -> True
  Subtype.Weird -> True
  Subtype.Werewolf -> True
  Subtype.Whale -> True
  Subtype.Wizard -> True
  Subtype.Wolf -> True
  Subtype.Wolverine -> True
  Subtype.Wombat -> True
  Subtype.Worm -> True
  Subtype.Wraith -> True
  Subtype.Wurm -> True
  Subtype.Yeti -> True
  Subtype.Zombie -> True
  Subtype.Zubera -> True
  _ -> False
