module Pawl.Types.CombatRestriction where

import qualified Pawl.Types.AffectedUnless as AffectedUnless
import qualified Pawl.Types.CantBeBlockedBy as CantBeBlockedBy
import qualified Pawl.Types.LimitUnless as LimitUnless

-- | CR 508.1c / CR 509.1b: one printed COMBAT RESTRICTION -- an effect saying a
-- creature can't attack, can't attack alone, or can't attack unless some
-- condition is met, and the sentence CR 509.1b writes with "block" in place of
-- "attack". Pacifism states two of those in one line, and prints one of each of
-- the first two arms below.
--
-- The FIFTH carrier of a printed static ability, alongside
-- Pawl.Types.StaticAbility, Pawl.Types.PlayerStaticAbility,
-- Pawl.Types.BlockRequirement and Pawl.Types.AttackRequirement.
-- Pawl.Types.BlockRequirement's header argues why neither of the first two can
-- hold a REQUIREMENT, and every step of that argument holds here unchanged:
-- CR 613.1's layers compute an OBJECT's characteristics and "can't attack" is
-- not one of them, and PlayerScope names PLAYERS where this names a creature.
--
-- What is different is that this is ONE type where the requirements are two, and
-- the reason is the AXIS. CR 508.1d and CR 509.1c each imply a subject and an
-- object, and the two requirement carriers collapse opposite ones -- a blocking
-- requirement carries the attacker to be blocked and no subject, an attacking
-- requirement carries the subject and no object. A restriction names its SUBJECT
-- on every arm that names anything, and only CantBeBlockedBy also names an
-- object: Pacifism's two halves are the same Affected twice, so the only thing
-- distinguishing THOSE TWO is which declaration they forbid. Splitting them
-- would copy the requirements' shape without the reason for it. What tells the
-- later arms from the first is not the declaration -- CantAttackAlone and
-- CantAttackMoreThan both forbid an attack -- but the shape, which is the next
-- paragraph.
--
-- The arms differ in SHAPE rather than in axis, and there are four shapes. The
-- first two are answered about ONE CREATURE, so the reader may apply them to CR
-- 508.1a's and CR 509.1a's candidate list and never look at a declaration.
-- CantAttackAlone cannot be: it is a fact about the whole set of creatures
-- declared as attackers, so it is answered against the finished declaration
-- instead. Both are restrictions of the rule they name all the same -- CR 508.1c's
-- own Example is a "can't attack alone" board -- so they share the type rather
-- than splitting into a second carrier.
--
-- The THIRD shape bounds the SIZE of a declaration from above, which is Silent
-- Arbiter's "no more than one creature can attack each combat". CantAttackAlone
-- is not it turned around: it NAMES creatures and asks whether the declaration
-- holds one of them and nothing else, where a bound names no creature at all --
-- so those two arms carry a NUMBER where every other arm carries an Affected,
-- and no Affected could have stood in for it. CR 508.1d's own Example writes the
-- sentence with no subject to name -- "An effect states 'No more than one
-- creature can attack each turn.'" -- and a vacuous Affected would be read by
-- Pawl.Engine.CombatRestriction and reported by Pawl.CardSpec as card data the
-- card does not print. Like CantAttackAlone and unlike CantAttack, a bound
-- subtracts nothing from CR 508.1a's or CR 509.1a's candidate list: every
-- creature stays a legal candidate and it is the DECLARATION that is refused.
--
-- The FOURTH shape is answered about a PAIR, which is CantBeBlockedBy: it names
-- attackers and describes the blockers that may not block them, so no set of
-- creatures on either side is the answer, and CR 509.1b's own Example is a
-- pairwise board. It is the shape that rule's second paragraph is about, though
-- not always its evasion ABILITY: that paragraph's definition wants the ability
-- on the attacking creature, and CR 701.54c's is on an emblem.
--
-- A restriction a player may PAY THROUGH is one of CR 508.1c's all the same
-- (Ghostly Prison), but it rides Pawl.Types.AttackCost, the SIXTH carrier. The
-- split is pawl's, not the rules': CantAttack's answer is a SET OF CREATURES that
-- may not attack, and it takes its subject off CR 508.1a's candidate list
-- entirely, where a taxed creature has to stay on it. CantAttackAlone does leave
-- its subject on that list, and is no better a home: it forbids a DECLARATION,
-- where a cost is something a declaration pays, and it says nothing about how
-- many creatures are declared beside a taxed one. A cost is also a thing to be
-- PAID rather than a fact to be read, and CR 508.1d makes paying it optional, so
-- it could not be a Condition either.
--
-- A restriction whose CONDITION is about the DEFENDING PLAYER (Armored Galleon,
-- Crown-Hunter Hireling) needs no arm of its own: the condition below says it,
-- through Pawl.Types.Filter.ControlledByDefendingPlayer, and
-- Pawl.Engine.CombatRestriction.inForce is what supplies CR 508.5's answer.
--
-- NOT IMPLEMENTED: an attacking restriction naming WHAT the attack is aimed at
-- (Blazing Archon, "creatures can't attack you"), which is CR 508.1b's
-- per-creature announcement rather than a condition (#1686). The blocking side's
-- object is CantBeBlockedBy, whose own comment says why a keyword on the
-- attacker could not have carried CR 701.54c's clause.
--
-- Open-half card data, classified rather than identified:
-- Pawl.Engine.CombatRestriction is the only module that may case on it. Casing
-- here is casing on which rulebook declaration a restriction forbids and in what
-- shape, not on an effect's identity.
--
-- Card data is not ALL it carries. Rule 702 mints one of these from a keyword
-- (unleash, CR 702.98a), which is the closed half writing its own rules rather
-- than a card writing text -- the position Pawl.Types.EntryRewrite.Riot is in.
--
-- Gathered LIVE on every read and never captured, the posture all five siblings
-- take -- from the battlefield, and from the command zone for an emblem, whose
-- abilities CR 114.4 makes function there -- so a Pacifism leaving the
-- battlefield lifts its restriction with nothing to unwind. The gate is re-read
-- on the same schedule: CR 508.1 and CR 509.1 make the declaration a SEQUENCE OF STEPS, of
-- which CR 508.1c and CR 509.1b are one, so the only moment a gate's answer has
-- to be right is the moment it is asked, and a gate that stops holding
-- re-imposes the restriction with nothing to unwind either. CR 509.1b's note
-- that an evasion
-- ability gained after a legal block does not affect that block is the rules
-- saying the same thing.
--
-- The LAST field of each arm is that gate: the condition the creature can't
-- attack (or block) UNLESS -- Blind-Spot Giant's "unless you control another
-- Giant". On the two bound arms it gates the whole sentence rather than a
-- creature, which is the same clause CR 508.1c describes and the same posture
-- CantAttackAlone's gate is in: nothing in the pool prints a gated one, and the
-- field is there because whether a restriction is gated is independent of its
-- shape rather than because a card asks. Nothing is the unconditional
-- restriction (Pacifism), which is not the same as a condition that never
-- holds: the two would answer alike today, but
-- only one of them is what the card says. A Condition states the gate because
-- CR 508.1c's condition is a predicate over game STATE, which is the type
-- Pawl.Types.Condition already is.
--
-- The "you" inside the condition is CR 109.5's: the controller of the permanent
-- the restriction is printed on, which is not necessarily the controller of the
-- creature it restricts. Blind-Spot Giant is its own source and cannot tell them
-- apart; a conditional Aura would.
data CombatRestriction
  = -- | CR 508.1c: these creatures can't attack, unless the gate holds. Pacifism
    -- (ungated) and Blind-Spot Giant (gated) are the pool's printed attacking
    -- restrictions that are not CR 702.3b's defender keyword, which stays a
    -- Keyword because rule 702 is part of the rulebook and a keyword's meaning
    -- is the closed half's to know.
    CantAttack AffectedUnless.AffectedUnless
  | -- | CR 509.1b: these creatures can't block, unless the gate holds.
    -- Pacifism's second half and Blind-Spot Giant's are the pool's only printed
    -- blocking restrictions, and CR 702.98a's unleash is the one rule 702 mints
    -- (Pawl.Engine.Keyword.mintedCombatRestrictionsFor); every other one today
    -- restricts being blocked rather than blocking, as an evasion keyword on the
    -- ATTACKER or as the arm below.
    CantBlock AffectedUnless.AffectedUnless
  | -- | CR 509.1b's second paragraph: these ATTACKING creatures can't be blocked
    -- by creatures matching the Filter, unless the gate holds. CR 701.54c's "your
    -- Ring-bearer ... can't be blocked by creatures with greater power" is the
    -- pool's one statement of it (Pawl.Engine.Ring.theRingCantBeBlockedByGreaterPower).
    --
    -- The one arm carrying an OBJECT as well as a subject, because a pair is the
    -- smallest thing the sentence is about: the Filter describes a blocker
    -- RELATIVE TO the attacker it may not block ("with greater power"), so
    -- neither a set of attackers nor a set of blockers is an answer, and the two
    -- sides cannot be split into two restrictions.
    --
    -- Not a keyword on the attacker, which is where every other evasion ability
    -- lives (CR 702.9b's flying, CR 702.118b's skulk -- whose text this clause
    -- otherwise repeats word for word). CR 701.54c prints the sentence on THE
    -- EMBLEM rather than on the creature: the Ring-bearer is not given skulk and
    -- does not answer a "creature with skulk" filter, the designation can move to
    -- another creature between blocks, and nothing on the Ring-bearer's own card
    -- says any of it. A keyword grant would be observably the wrong reading on
    -- all three counts.
    --
    -- The Filter's context is the ATTACKER's, which is what makes the comparison
    -- expressible: Filter.PowerGreaterThanSource reads
    -- Pawl.Engine.Filter.Context's sourcePower, and the power CR 701.54c compares
    -- against is the blocked creature's, not the emblem's -- CR 114.3 leaves an
    -- emblem no power at all. See Pawl.Engine.CombatRestriction.cantBeBlockedBy.
    CantBeBlockedBy CantBeBlockedBy.CantBeBlockedBy
  | -- | CR 508.1c together with CR 506.5: these creatures can't be the ONLY
    -- creature declared as an attacker, unless the gate holds. Bonded Construct
    -- ("This creature can't attack alone") is the pool's printing, and CR
    -- 508.1c's own Example is a board of two of them.
    --
    -- Not CantAttack with a Condition, and the difference is not expressible as
    -- one: CR 506.5's "alone" is a fact about the DECLARATION being written, and
    -- a Condition is a predicate over game state, which at CR 508.1c time cannot
    -- see a declaration that has not been made. That is also why this arm exists
    -- rather than a cleverer Affected -- Affected names creatures, and no set of
    -- creatures says "however many of you there are".
    --
    -- The gate beside it is the same "unless" every arm carries, and is about
    -- game state as usual: nothing in the pool prints a gated one.
    CantAttackAlone AffectedUnless.AffectedUnless
  | -- | CR 508.1c: no more than this many creatures may be declared as
    -- attackers, unless the gate holds. Silent Arbiter's first sentence, and
    -- the board CR 508.1d's Example is written about.
    --
    -- The card says "each combat" where this is asked of a DECLARATION, and the
    -- two name the same event by RULE rather than by coincidence: CR 506.1
    -- gives a combat phase exactly one declare attackers step, and CR 703.4i
    -- makes Pawl.Engine.Combat.declareAttackers that step's turn-based action.
    -- So nothing needs storing and nothing needs resetting -- the bound is
    -- re-read live off the battlefield like every sibling above, and a second
    -- combat phase in the same turn (Relentless Assault, Aggravated Assault)
    -- gets a fresh reading rather than a running tally, which is what "each
    -- combat" asks for and what CR 508.1d's last sentence says of the
    -- requirements on the other side of the same check.
    --
    -- CR 508.4c closes the remaining gap: a creature put onto the battlefield
    -- attacking is not affected by restrictions that apply to the declaration,
    -- so a creature joining combat outside the declaration is exempt by rule
    -- rather than by pawl's omission, and a per-phase tally would have had to
    -- exclude it anyway.
    CantAttackMoreThan LimitUnless.LimitUnless
  | -- | CR 509.1b, the same bound on the other declaration. Silent Arbiter's
    -- second sentence, and the arm above's reasoning holds unchanged: CR 506.1
    -- gives a combat phase one declare blockers step, CR 703.4j makes
    -- Pawl.Engine.Combat.declareBlockers its turn-based action, and CR 509.1a
    -- names a single defending player to make it.
    CantBlockMoreThan LimitUnless.LimitUnless
  deriving (Eq, Ord, Show)
