module Pawl.Types.Expansion where

import qualified Data.Map as Map
import qualified Data.Set as Set
import qualified Data.Text as Text
import qualified Pawl.Types.CardName as CardName

-- | The short code naming one Magic expansion -- "ARN", "ATQ", "HML" -- as the
-- CR 206.3 errata names a set.
--
-- A wrapper over a code rather than an enum, for Pawl.Types.CardName's reason:
-- the codes are open, and only the three CR 206.3 spells out resolve today.
--
-- 'UnsafeMkExpansion' rather than @MkExpansion@, Pawl.Types.CounterName's
-- shape: the bare constructor sidesteps the invariant that the code names an
-- expansion 'catalog' knows. The door that maintains it is
-- Pawl.Codec.Expansion.make, and card data reaches this type only through it.
newtype Expansion = UnsafeMkExpansion
  { unwrap :: Text.Text
  }
  deriving (Eq, Ord, Show)

-- | The names CR 206.3 says were originally printed in an expansion, or Nothing
-- for a code the rule does not name. Nothing rather than an empty set: an
-- unresolved code is broken card data, which Pawl.Codec.Expansion.make refuses
-- rather than answering "matches nothing".
names :: Expansion -> Maybe (Set.Set CardName.CardName)
names expansion = Map.lookup expansion catalog

-- | CR 206.3a-c, and the only copy: Pawl.Codec.Expansion reads it to refuse an
-- unresolved code, and Pawl.Engine.Filter reads it to answer
-- 'Pawl.Types.Filter.HasNameOriginallyPrintedIn'. It sits beside the type
-- because those two sublibraries share only this one.
--
-- The rule DEFINES these sets, so they belong to the rulebook rather than to a
-- card, and no card enumerates them -- CR 205.3m's every-creature-type list is
-- the same kind of payload.
--
-- Two spellings differ from the printed rule, both because these are compared
-- against PROJECTED names, which are Oracle's: the rule's curly apostrophes are
-- the ASCII apostrophe every card file writes, and the rule's "Ifh-Biff Efreet"
-- is Oracle's accented spelling (api.scryfall.com, 2026-09-06). The accents are
-- the style guide's ASCII preference deviated from, and unavoidable: these are
-- the names.
catalog :: Map.Map Expansion (Set.Set CardName.CardName)
catalog =
  Map.fromList
    [ -- CR 206.3a: Arabian Nights, which City in a Bottle names.
      ( UnsafeMkExpansion (Text.pack "ARN"),
        fromNames
          [ "Abu Ja'far",
            "Aladdin",
            "Aladdin's Lamp",
            "Aladdin's Ring",
            "Ali Baba",
            "Ali from Cairo",
            "Army of Allah",
            "Bazaar of Baghdad",
            "Bird Maiden",
            "Bottle of Suleiman",
            "Brass Man",
            "Camel",
            "City in a Bottle",
            "City of Brass",
            "Cuombajj Witches",
            "Cyclone",
            "Dancing Scimitar",
            "Dandân",
            "Desert",
            "Desert Nomads",
            "Desert Twister",
            "Diamond Valley",
            "Drop of Honey",
            "Ebony Horse",
            "Elephant Graveyard",
            "El-Hajjâj",
            "Erg Raiders",
            "Erhnam Djinn",
            "Eye for an Eye",
            "Fishliver Oil",
            "Flying Carpet",
            "Flying Men",
            "Ghazbán Ogre",
            "Giant Tortoise",
            "Guardian Beast",
            "Hasran Ogress",
            "Hurr Jackal",
            "Ifh-Bíff Efreet",
            "Island Fish Jasconius",
            "Island of Wak-Wak",
            "Jandor's Ring",
            "Jandor's Saddlebags",
            "Jeweled Bird",
            "Jihad",
            "Junún Efreet",
            "Juzám Djinn",
            "Khabál Ghoul",
            "King Suleiman",
            "Kird Ape",
            "Library of Alexandria",
            "Magnetic Mountain",
            "Merchant Ship",
            "Metamorphosis",
            "Mijae Djinn",
            "Moorish Cavalry",
            "Nafs Asp",
            "Oasis",
            "Old Man of the Sea",
            "Oubliette",
            "Piety",
            "Pyramids",
            "Repentant Blacksmith",
            "Ring of Ma'rûf",
            "Rukh Egg",
            "Sandals of Abdallah",
            "Sandstorm",
            "Serendib Djinn",
            "Serendib Efreet",
            "Shahrazad",
            "Sindbad",
            "Singing Tree",
            "Sorceress Queen",
            "Stone-Throwing Devils",
            "Unstable Mutation",
            "War Elephant",
            "Wyluli Wolf",
            "Ydwen Efreet"
          ]
      ),
      -- CR 206.3b: Antiquities, which Golgothian Sylex names.
      ( UnsafeMkExpansion (Text.pack "ATQ"),
        fromNames
          [ "Amulet of Kroog",
            "Argivian Archaeologist",
            "Argivian Blacksmith",
            "Argothian Pixies",
            "Argothian Treefolk",
            "Armageddon Clock",
            "Artifact Blast",
            "Artifact Possession",
            "Artifact Ward",
            "Ashnod's Altar",
            "Ashnod's Battle Gear",
            "Ashnod's Transmogrant",
            "Atog",
            "Battering Ram",
            "Bronze Tablet",
            "Candelabra of Tawnos",
            "Circle of Protection: Artifacts",
            "Citanul Druid",
            "Clay Statue",
            "Clockwork Avian",
            "Colossus of Sardia",
            "Coral Helm",
            "Crumble",
            "Cursed Rack",
            "Damping Field",
            "Detonate",
            "Drafna's Restoration",
            "Dragon Engine",
            "Dwarven Weaponsmith",
            "Energy Flux",
            "Feldon's Cane",
            "Gaea's Avenger",
            "Gate to Phyrexia",
            "Goblin Artisans",
            "Golgothian Sylex",
            "Grapeshot Catapult",
            "Haunting Wind",
            "Hurkyl's Recall",
            "Ivory Tower",
            "Jalum Tome",
            "Martyrs of Korlis",
            "Mightstone",
            "Millstone",
            "Mishra's Factory",
            "Mishra's War Machine",
            "Mishra's Workshop",
            "Obelisk of Undoing",
            "Onulet",
            "Orcish Mechanics",
            "Ornithopter",
            "Phyrexian Gremlins",
            "Power Artifact",
            "Powerleech",
            "Priest of Yawgmoth",
            "Primal Clay",
            "The Rack",
            "Rakalite",
            "Reconstruction",
            "Reverse Polarity",
            "Rocket Launcher",
            "Sage of Lat-Nam",
            "Shapeshifter",
            "Shatterstorm",
            "Staff of Zegon",
            "Strip Mine",
            "Su-Chi",
            "Tablet of Epityr",
            "Tawnos's Coffin",
            "Tawnos's Wand",
            "Tawnos's Weaponry",
            "Tetravus",
            "Titania's Song",
            "Transmute Artifact",
            "Triskelion",
            "Urza's Avenger",
            "Urza's Chalice",
            "Urza's Mine",
            "Urza's Miter",
            "Urza's Power Plant",
            "Urza's Tower",
            "Wall of Spears",
            "Weakstone",
            "Xenic Poltergeist",
            "Yawgmoth Demon",
            "Yotian Soldier"
          ]
      ),
      -- CR 206.3c: Homelands, which Apocalypse Chime names.
      ( UnsafeMkExpansion (Text.pack "HML"),
        fromNames
          [ "Abbey Gargoyles",
            "Abbey Matron",
            "Aether Storm",
            "Aliban's Tower",
            "Ambush",
            "Ambush Party",
            "Anaba Ancestor",
            "Anaba Bodyguard",
            "Anaba Shaman",
            "Anaba Spirit Crafter",
            "An-Havva Constable",
            "An-Havva Inn",
            "An-Havva Township",
            "An-Zerrin Ruins",
            "Apocalypse Chime",
            "Autumn Willow",
            "Aysen Abbey",
            "Aysen Bureaucrats",
            "Aysen Crusader",
            "Aysen Highway",
            "Baki's Curse",
            "Baron Sengir",
            "Beast Walkers",
            "Black Carriage",
            "Broken Visage",
            "Carapace",
            "Castle Sengir",
            "Cemetery Gate",
            "Chain Stasis",
            "Chandler",
            "Clockwork Gnomes",
            "Clockwork Steed",
            "Clockwork Swarm",
            "Coral Reef",
            "Dark Maze",
            "Daughter of Autumn",
            "Death Speakers",
            "Didgeridoo",
            "Drudge Spell",
            "Dry Spell",
            "Dwarven Pony",
            "Dwarven Sea Clan",
            "Dwarven Trader",
            "Ebony Rhino",
            "Eron the Relentless",
            "Evaporate",
            "Faerie Noble",
            "Feast of the Unicorn",
            "Feroz's Ban",
            "Folk of An-Havva",
            "Forget",
            "Funeral March",
            "Ghost Hounds",
            "Giant Albatross",
            "Giant Oyster",
            "Grandmother Sengir",
            "Greater Werewolf",
            "Hazduhr the Abbot",
            "Headstone",
            "Heart Wolf",
            "Hungry Mist",
            "Ihsan's Shade",
            "Irini Sengir",
            "Ironclaw Curse",
            "Jinx",
            "Joven",
            "Joven's Ferrets",
            "Joven's Tools",
            "Koskun Falls",
            "Koskun Keep",
            "Labyrinth Minotaur",
            "Leaping Lizard",
            "Leeches",
            "Mammoth Harness",
            "Marjhan",
            "Memory Lapse",
            "Merchant Scroll",
            "Mesa Falcon",
            "Mystic Decree",
            "Narwhal",
            "Orcish Mine",
            "Primal Order",
            "Prophecy",
            "Rashka the Slayer",
            "Reef Pirates",
            "Renewal",
            "Retribution",
            "Reveka, Wizard Savant",
            "Root Spider",
            "Roots",
            "Roterothopter",
            "Rysorian Badger",
            "Samite Alchemist",
            "Sea Sprite",
            "Sea Troll",
            "Sengir Autocrat",
            "Sengir Bats",
            "Serra Aviary",
            "Serra Bestiary",
            "Serra Inquisitors",
            "Serra Paladin",
            "Serrated Arrows",
            "Shrink",
            "Soraya the Falconer",
            "Spectral Bears",
            "Timmerian Fiends",
            "Torture",
            "Trade Caravan",
            "Truce",
            "Veldrane of Sengir",
            "Wall of Kelp",
            "Willow Faerie",
            "Willow Priestess",
            "Winter Sky",
            "Wizards' School"
          ]
      )
    ]

-- | 'catalog' reads as the rule's own lists this way; spelling
-- 'CardName.MkCardName' beside each of the names would not.
fromNames :: [String] -> Set.Set CardName.CardName
fromNames = Set.fromList . fmap (CardName.MkCardName . Text.pack)
