module Pawl.Types.PlayerScope where

-- A SET of players, named relative to a perspective: the player-side analogue of
-- Pawl.Types.Affected, and much smaller because CR 109.5 fixes what "you" means.
-- Membership is Pawl.Engine.PlayerEffect.inScope and the set is the fold over it,
-- Pawl.Engine.PlayerEffect.playersInScope -- one reading, two shapes.
--
-- Two carriers, and CR 109.5's "you" is the perspective for both; they differ
-- only in where that player comes from:
--
--   * Pawl.Types.PlayerStaticAbility / ActivePlayerEffect -- which players a
--     Pawl.Types.PlayerEffect applies to, against the effect's CONTROLLER ("for
--     a static ability, this is the current controller of the object it's on").
--   * Pawl.Types.Pool.CardsInGraveyard -- whose graveyards a target slot draws
--     from (CR 400.1), against the perspective the targeting carries. That
--     carrier is why this is not Pawl.Types.PlayerRef, whose InSlot arm names a
--     target slot CR 601.2c has not filled yet; see Pool's own note.
--
-- The scope is always resolved DYNAMICALLY on both PlayerEffect carriers. CR
-- 611.2c's first sentence freezes a stored effect's object set -- which is what
-- every stored ContinuousEffect does (Affected.TheseObjects) -- but its third
-- sentence carves out exactly this axis: "A continuous effect generated by the
-- resolution of a spell or ability that doesn't modify the characteristics or
-- change the controller of any objects modifies the rules of the game, so it can
-- affect objects that weren't affected when that continuous effect began." So
-- there is no stored-set analogue of TheseObjects here and no one-way door: this
-- is the same type on the printed and the stored carrier. Freeze it and Silence,
-- which resolves with no opponent spell on the stack, does literally nothing.
data PlayerScope
  = -- CR 109.5: the effect's controller.
    You
  | -- Every other player. Not a two-player shortcut: CR 806.1 has a
    -- free-for-all's players compete as individuals against each other, so
    -- every other player is an opponent by construction; CR 102.2 says the
    -- same thing for two players. `Pawl.Engine.PlayerEffect.inScope`'s
    -- `pid /= controller` is the one predicate that serves both. CR 102.3 is
    -- the ONE reading this is wrong for -- a teammate is not an opponent --
    -- and pawl has no teams to express (#175).
    --
    -- Pinned at three seats by PlayerEffectSpec's "CR 806.1 at three seats
    -- Silence stops BOTH opponents, and still spares the caster".
    Opponents
  | -- Every player, the controller included ("including your own", Thalia's own
    -- ruling).
    EachPlayer
  deriving (Eq, Ord, Show)
