{-# LANGUAGE GADTs #-}

module Pawl.Types.Prompt where

import qualified Data.List.NonEmpty as NonEmpty
import qualified Data.Map.Strict as Map
import qualified Data.Sequence as Seq
import qualified Data.Set as Set
import qualified Numeric.Natural as Natural
import qualified Pawl.Types.Action as Action
import qualified Pawl.Types.AttackTarget as AttackTarget
import qualified Pawl.Types.CardName as CardName
import qualified Pawl.Types.ClauseIndex as ClauseIndex
import qualified Pawl.Types.Color as Color
import qualified Pawl.Types.CommandZoneDecision as CommandZoneDecision
import qualified Pawl.Types.Concession as Concession
import qualified Pawl.Types.Cost as Cost
import qualified Pawl.Types.DamageEvent as DamageEvent
import qualified Pawl.Types.Decider as Decider
import qualified Pawl.Types.EntryOption as EntryOption
import qualified Pawl.Types.EntwineDecision as EntwineDecision
import qualified Pawl.Types.Filter as Filter
import qualified Pawl.Types.HandActionIndex as HandActionIndex
import qualified Pawl.Types.HybridPayment as HybridPayment
import qualified Pawl.Types.Keyword as Keyword
import qualified Pawl.Types.LibraryPosition as LibraryPosition
import qualified Pawl.Types.ManaOption as ManaOption
import qualified Pawl.Types.ManaSymbol as ManaSymbol
import qualified Pawl.Types.ManaType as ManaType
import qualified Pawl.Types.ModeIndex as ModeIndex
import qualified Pawl.Types.ModeSelection as ModeSelection
import qualified Pawl.Types.MulliganDecision as MulliganDecision
import qualified Pawl.Types.MulliganOffer as MulliganOffer
import qualified Pawl.Types.ObjectId as ObjectId
import qualified Pawl.Types.OptionalDecision as OptionalDecision
import qualified Pawl.Types.PaymentDecision as PaymentDecision
import qualified Pawl.Types.PhyrexianPayment as PhyrexianPayment
import qualified Pawl.Types.PlayerId as PlayerId
import qualified Pawl.Types.Recipient as Recipient
import qualified Pawl.Types.ReplacementEntry as ReplacementEntry
import qualified Pawl.Types.SlotName as SlotName
import qualified Pawl.Types.Subtype as Subtype
import qualified Pawl.Types.TriggerEntry as TriggerEntry

data Prompt r where
  ChooseAction :: Decider.Decider -> PlayerId.PlayerId -> [Action.Action] -> Prompt Action.Action
  -- | CR 104.3a: a player may concede at any time. Asked before ChooseAction
  -- wherever a player would receive priority.
  --
  -- The only CHOICE prompt carrying no Decider, and that asymmetry IS CR 723.6's
  -- mechanism: the ask must reach the true player, and there must be nowhere to
  -- put a controller. Folding concede into ChooseAction would hand the controller
  -- exactly the power that rule forbids. (Shuffle and RandomFirstPlayer carry no
  -- Decider either, for the unrelated reason that randomness is not a choice.)
  --
  -- "At any time" is narrowed to "at each priority grant", and while a CR 729
  -- subgame runs this asks about the SUBGAME rather than the main game (#144,
  -- #397).
  Concede :: PlayerId.PlayerId -> Prompt Concession.Concession
  Shuffle :: [ObjectId.ObjectId] -> Prompt [ObjectId.ObjectId]
  -- | CR 729.2: randomly determine which player goes first. The NonEmpty is the
  -- turn order; the answer is the starting player, and the order is then rotated
  -- to begin with them (CR 103.1).
  --
  -- Carries no Decider, and neither does Shuffle: randomness is not a choice, so
  -- there is no decision to usurp and nowhere for a CR 723 controller to sit.
  -- Asked only where the rules call for randomness -- a subgame's start. A main
  -- game's starting player is settled before the game begins (CR 103.1), which is
  -- the caller-supplied turn order Setup.emptyGame takes.
  --
  -- NonEmpty rather than []: the answer has to come from somewhere and a fallback
  -- must be total.
  RandomFirstPlayer :: NonEmpty.NonEmpty PlayerId.PlayerId -> Prompt PlayerId.PlayerId
  -- | CR 514.2. The [ObjectId] is the hand; the Natural is how many to discard.
  ChooseDiscard :: Decider.Decider -> PlayerId.PlayerId -> [ObjectId.ObjectId] -> Natural.Natural -> Prompt [ObjectId.ObjectId]
  -- | CR 507.1 / 703.4h: the active player chooses one of their opponents to be
  -- the defending player. The NonEmpty is the candidates; the answer is the one
  -- chosen.
  --
  -- NonEmpty rather than []: a fallback must be total. No opponents at all cannot
  -- arise while the game runs (CR 104.2a), and is handled by not performing the
  -- action, leaving Combat.defender at Nothing -- not a claim about legality,
  -- since Combat.canAttack never reads that field.
  --
  -- Not asked when there is exactly one candidate (#169): CR 507.1 makes the
  -- choice exist only in a multiplayer game, and a two-player game gets its
  -- defending player from CR 506.2.
  ChooseDefender :: Decider.Decider -> PlayerId.PlayerId -> NonEmpty.NonEmpty PlayerId.PlayerId -> Prompt PlayerId.PlayerId
  -- | CR 601.2g (and CR 602.2b for an ability): which mana source to activate next
  -- while paying a cost the pool does NOT yet cover.
  --
  -- Asked once per source TAPPED, against a shrinking candidate list, which is
  -- not once per mana the cost demands: a Sol Ring pays {2} in one activation and
  -- so raises this once.
  --
  -- Nothing DECLINES, which is CR 118.3c: activating mana abilities is not
  -- mandatory even when paying is. The payment then comes up short and fails, and
  -- CR 601.2h reverses whatever proposed it.
  --
  -- Never elided, not even for a single candidate, because declining is a real
  -- answer on every board -- ChooseProliferate's posture. Same-card candidates
  -- are NOT treated as interchangeable either: two Llanowar Elves can differ by
  -- an Equipment, an Aura, counters or borrowed control, and none of that is
  -- visible in the printed card (#12, #217).
  ChooseManaSource :: Decider.Decider -> PlayerId.PlayerId -> NonEmpty.NonEmpty ObjectId.ObjectId -> Prompt (Maybe ObjectId.ObjectId)
  -- | CR 605.3a, asked once the pool ALREADY covers the cost: which further mana
  -- source to activate, or Nothing to close CR 601.2g's window and pay. That
  -- permission is not rationed by what the cost needs, so a player may keep
  -- going.
  --
  -- A sibling of ChooseManaSource rather than the same constructor because the
  -- two windows differ in what silence means -- there, declining fails the
  -- payment; here, it pays. That is what lets a caller with no player attached
  -- (Pawl.Engine.Replay.defaultAnswer) answer each one sensibly: take the first
  -- source while short, float nothing once covered.
  --
  -- Floating is a real decision because unspent mana can be read: Omnath, Locus
  -- of Mana gets +1/+1 for each green mana its controller has, so a player who
  -- taps only what the cost needs has made their creature smaller.
  --
  -- Never elided: finishing is always an answer, so even one candidate is a real
  -- question.
  ChooseExtraManaSource :: Decider.Decider -> PlayerId.PlayerId -> NonEmpty.NonEmpty ObjectId.ObjectId -> Prompt (Maybe ObjectId.ObjectId)
  -- | CR 605.3b: which mana the source produces, asked as the mana ability
  -- resolves -- immediately, a mana ability never using the stack. The answer is a
  -- Pawl.Types.ManaOption, the whole mana one activation adds together with what
  -- CR 602.2b charges for it, so "{T}: Add {C}{C}" is one candidate of two units.
  -- Four things reach this one prompt, being observationally the same question:
  --
  --   * one AddMana effect offering a choice, whose options are CR 105.4's colours;
  --   * a permanent with several single-type mana abilities, an Urborg'd Mountain
  --     being both a Mountain and a Swamp (CR 305.6/305.7);
  --   * a mana ability with several MODES (CR 700.2), which no card in the pool
  --     has; and
  --   * two abilities adding the same mana for DIFFERENT costs, an Urborg'd Mana
  --     Confluence's free {B} beside the {B} it charges 1 life for (#1117).
  --
  -- Collapsing them is sound because a source taps once, so all four are one
  -- question: which single activation.
  --
  -- Candidates are deduplicated by the whole option (Mana.manaOptionsOf), the one
  -- elision needing no judgement: two ways to produce black mana for the same
  -- cost add the same mana and charge the same for it.
  ChooseManaYield :: Decider.Decider -> PlayerId.PlayerId -> ObjectId.ObjectId -> NonEmpty.NonEmpty ManaOption.ManaOption -> Prompt ManaOption.ManaOption
  -- | CR 701.34a: which permanents and players a proliferating player gives another
  -- counter to. The lists are every permanent and player holding at least one
  -- counter; the answer is the subset of each that gets one more of every kind it
  -- already has.
  --
  -- CHOOSE, not target: proliferate declares no target spec, so a candidate is
  -- offered whoever's it is, and nothing is re-checked at resolution (CR 608.2b).
  --
  -- Asked whenever either list is non-empty, elided only when both are empty.
  -- Deliberately not elided for a single candidate, ChooseManaSource's posture:
  -- "any number" includes none, so even one candidate is a real yes or no.
  ChooseProliferate :: Decider.Decider -> PlayerId.PlayerId -> [ObjectId.ObjectId] -> [PlayerId.PlayerId] -> Prompt (Set.Set ObjectId.ObjectId, Set.Set PlayerId.PlayerId)
  -- | CR 701.54a: which creature a tempted player controls becomes their
  -- Ring-bearer. The NonEmpty is the creatures they control; the answer is the ONE
  -- that takes the designation.
  --
  -- CHOOSE, not target: rule 701.54a says "choose a creature you control", so no
  -- target spec is declared and nothing is re-checked at resolution (CR 608.2b).
  --
  -- Raised only for TWO OR MORE candidates, ChooseLegend's shape. One creature is
  -- not a choice: the action is mandatory and has exactly one legal answer, so
  -- performing it is not the engine deciding anything. It is emphatically not an
  -- elision of ChooseProliferate's kind, whose "any number" makes even a lone
  -- candidate a real yes or no.
  --
  -- NOT raised at all for zero candidates, and that is CR 701.54d rather than an
  -- omission: the player is tempted anyway, so Pawl.Engine.Ring.tempt still counts
  -- the temptation and still gives them the emblem.
  ChooseRingBearer :: Decider.Decider -> PlayerId.PlayerId -> NonEmpty.NonEmpty ObjectId.ObjectId -> Prompt ObjectId.ObjectId
  -- | CR 704.5j: which of two or more same-named legendary permanents its
  -- controller keeps. The NonEmpty is the whole same-named group; the answer is the
  -- ONE that survives.
  --
  -- One prompt per name, not per player: a player controlling two pairs faces two
  -- separate applications of the legend rule.
  --
  -- The answer is what is KEPT rather than what is buried, which is how CR 704.5j
  -- is worded and stays a single choice however large the group gets.
  --
  -- Never elided: the prompt is only raised for a group of two or more, and the
  -- permanents may differ in counters, Auras, damage or summoning sickness, none of
  -- which the shared name can see.
  ChooseLegend :: Decider.Decider -> PlayerId.PlayerId -> NonEmpty.NonEmpty ObjectId.ObjectId -> Prompt ObjectId.ObjectId
  -- | CR 508.1a. The [ObjectId] is the legal attackers; the answer is which of them
  -- attack. WHAT each one attacks is a SEPARATE question, asked once per chosen
  -- creature by ChooseAttackTarget below, because CR 508.1b is a separate step of
  -- the declaration and asks per creature rather than per declaration.
  DeclareAttackers :: Decider.Decider -> PlayerId.PlayerId -> [ObjectId.ObjectId] -> Prompt [ObjectId.ObjectId]
  -- | CR 508.1b: the active player announces which player, planeswalker or battle
  -- each chosen creature is attacking. The ObjectId is the creature being
  -- announced; the NonEmpty is what it may attack, the defending player first.
  --
  -- One prompt PER CREATURE, which is what the rule asks for rather than a
  -- convenience -- a per-declaration answer would collapse a choice the rules keep
  -- apart.
  --
  -- CR 508.4 reaches this prompt too, for a creature put onto the battlefield
  -- attacking: same question, same candidates, same chooser (CR 506.3b). One prompt
  -- and not two, since an interpreter that could tell them apart would answer them
  -- identically.
  --
  -- Elided at exactly one candidate, which is CR 508.1b's own condition read
  -- backwards: with no planeswalker, no battle and one defending player the rule
  -- calls for no announcement.
  ChooseAttackTarget :: Decider.Decider -> PlayerId.PlayerId -> ObjectId.ObjectId -> NonEmpty.NonEmpty AttackTarget.AttackTarget -> Prompt AttackTarget.AttackTarget
  -- | CR 509.1. The legal blockers, then the attackers they may block. The answer
  -- maps each blocking creature to the attackers it blocks.
  --
  -- A SET per blocker, and never a single attacker: CR 509.1a gives a creature one
  -- attacker to block, but a permission can raise that (Foriysian Brigade), and
  -- fixed arity is the recurring root cause (design doc §2.11). A blocker that
  -- blocks nothing is absent rather than mapped to the empty set.
  --
  -- WHICH attackers each blocker may take is not offered per blocker: the
  -- restrictions are pairwise (CR 509.1b) and the arity is per creature, so the
  -- prompt hands over both lists and Pawl.Engine.Combat.legalBlockDeclaration
  -- judges the answer.
  DeclareBlockers :: Decider.Decider -> PlayerId.PlayerId -> [ObjectId.ObjectId] -> [ObjectId.ObjectId] -> Prompt (Map.Map ObjectId.ObjectId (Set.Set ObjectId.ObjectId))
  -- | CR 510.1 / 702.19b: a combatant divides its power among the legal
  -- recipients. The ObjectId is the assigning creature -- an ATTACKER under CR
  -- 510.1c, dividing among the creatures blocking it, or a BLOCKER under CR
  -- 510.1d, dividing among the creatures it blocks.
  --
  -- The Map is recipient -> lethal threshold (blockers -> lethal, the defender ->
  -- 0); trample-ness is entirely in whether the defender is a key and what the
  -- thresholds are. Every threshold is 0 on the blocking side, CR 510.1d imposing
  -- no minimum. Not asked when the division is forced (one recipient, no excess).
  -- Validation is Damage.legalAssignment. See the M2c spec, section 4.
  AssignCombatDamage :: Decider.Decider -> PlayerId.PlayerId -> ObjectId.ObjectId -> Map.Map Recipient.Recipient Natural.Natural -> Natural.Natural -> Prompt (Map.Map Recipient.Recipient Natural.Natural)
  -- | CR 601.2c. One legal-recipient set per named slot of the spell being cast
  -- (the ObjectId); the answer fills every slot. Slots agree by NAME, never by
  -- position. Not asked when the spell has no slots: zero slots is no choice
  -- at all, and where the rules leave nothing to ask, don't prompt.
  --
  -- The slots offered are the ones that WILL be filled: a CR 115.6 slot the
  -- caster declined at AnnounceTargets below is not among them.
  ChooseTargets :: Decider.Decider -> PlayerId.PlayerId -> ObjectId.ObjectId -> Map.Map SlotName.SlotName (Set.Set Recipient.Recipient) -> Prompt (Map.Map SlotName.SlotName Recipient.Recipient)
  -- | CR 601.2c's other announcement, made BEFORE ChooseTargets above: "If the
  -- spell has a variable number of targets, the player announces how many targets
  -- they will choose before they announce those targets."
  --
  -- The Map holds only the slots with a variable number -- CR 115.6's "up to one"
  -- -- and only those with at least one legal recipient, since zero is the sole
  -- answer for the rest. Every variable slot today is "up to one", so the count
  -- is 0 or 1 and the announcement IS the set of slots that will be filled; a
  -- count above one is a different gap (#1220). Not asked when the map is empty.
  --
  -- Carrying the candidate sets rather than the bare names, because the answer is
  -- a real decision and the player deciding needs to see what they would be
  -- aiming at.
  AnnounceTargets :: Decider.Decider -> PlayerId.PlayerId -> ObjectId.ObjectId -> Map.Map SlotName.SlotName (Set.Set Recipient.Recipient) -> Prompt (Set.Set SlotName.SlotName)
  -- | CR 612: choose the two basic land types for a text-changing spell's slot.
  --
  -- Asked AS THE EFFECT IS APPLIED, not as the spell is cast: CR 608.2d puts a
  -- choice that is not one of CR 601.2b-d's cast-time announcements at the
  -- application, and a word swap is none of those. So Resolve raises this and Cast
  -- does not. The ObjectId is the resolving spell.
  --
  -- The two moments are observably different even though the legal set is always
  -- the five basics and so never gates castability: a countered spell is never
  -- asked at all, and a player asked at cast would choose without information the
  -- responses gave them.
  --
  -- Named for the CR 612 word REPLACEMENT rather than for counting its payload --
  -- the pair is not what makes this prompt what it is, the swap is.
  --
  -- The Set is the words the NEW type may not be, stated by the text-changer's own
  -- card text. Empty for a card that restricts nothing, carried anyway so the two
  -- swap prompts present restrictions the same way.
  ChooseLandTypeSwap :: Decider.Decider -> PlayerId.PlayerId -> ObjectId.ObjectId -> SlotName.SlotName -> Set.Set Subtype.Subtype -> Prompt (Subtype.Subtype, Subtype.Subtype)
  -- | CR 612: ChooseLandTypeSwap's sibling for the other family CR 612.2 names, a
  -- creature type word used as a creature type.
  --
  -- Asked at the same moment and for the same CR 608.2d reason. Its own constructor
  -- rather than a family field on that one, because the two offer different words
  -- and a responder that knows which prompt it is answering knows which list.
  --
  -- The Set is the words the NEW type may not be, read off Effect.ChangeText, which
  -- reads it off the card -- such a restriction is printed card text, so it lives
  -- in the card's data rather than hard-coded here.
  --
  -- No candidate list, unlike ChooseLandTypeSwap's implied five: CR 205.3m's
  -- creature types run to hundreds, so the family is named rather than enumerated.
  -- Asked whenever the effect applies, with no one-option case to elide.
  ChooseCreatureTypeSwap :: Decider.Decider -> PlayerId.PlayerId -> ObjectId.ObjectId -> SlotName.SlotName -> Set.Set Subtype.Subtype -> Prompt (Subtype.Subtype, Subtype.Subtype)
  -- | CR 614.1c: as an object enters, its controller chooses ONE basic land
  -- type ("As this Aura enters, choose a basic land type" -- Convincing
  -- Mirage). The ObjectId is the entering object.
  --
  -- Singular, and deliberately not ChooseLandTypeSwap above. That prompt
  -- answers with a PAIR because CR 612's word swap needs two words (Magical
  -- Hack's "one basic land type" and the "another" replacing it); this is a
  -- single choice, made at a different moment (entry, not resolution) and by a
  -- different subsystem (Pawl.Engine.Replacement, not Pawl.Engine.Resolve).
  -- Answering it with a pair and dropping half would be the engine deciding
  -- something no player was asked.
  --
  -- No candidate list: CR 305.6 fixes the five basic land types ("The basic
  -- land types are Plains, Island, Swamp, Mountain, and Forest") the way CR
  -- 105.1 fixes the five colours for ChooseColor, and no card in the pool
  -- narrows them. Asked whenever the entering object has a controller to ask --
  -- five types are five distinguishable options, so there is no one-option case
  -- to elide. Pawl.Engine.Replacement's arm has an unreachable no-controller
  -- fallback beside it; see there.
  --
  -- No SlotName, unlike ChooseLandTypeSwap: that prompt names the spell's
  -- text-change slot, and this choice is bound into no slot at all -- it is
  -- written to Object.chosenSubtype on the entering permanent.
  ChooseBasicLandType :: Decider.Decider -> PlayerId.PlayerId -> ObjectId.ObjectId -> Prompt Subtype.Subtype
  -- | CR 701.23 / 701.23b: the [ObjectId] is the library cards MATCHING the
  -- criterion (the engine pre-filters to legal choices); Nothing is "fail to
  -- find," always permitted for a search of one's own library for a quality.
  SearchLibrary :: Decider.Decider -> PlayerId.PlayerId -> [ObjectId.ObjectId] -> Prompt (Maybe ObjectId.ObjectId)
  -- | CR 608.2g: the re-entrant cast opportunity during a library search (Panglacial
  -- Wurm) -- an effect that "specifically instructs or allows a player to cast a
  -- spell during resolution", following CR 601.2a-i except that no player receives
  -- priority after it is cast. Nothing = decline / done. Offered in a loop before
  -- the search finds (per the ruling), so multiple copies may be cast. CR 605.3a
  -- permits mana activation to pay.
  --
  -- ONE ENTRY PER CASTABLE HALF, paired with the name of the half being proposed
  -- (the engine pre-filters to permitted, affordable, fillable). The name is what
  -- CR 709.3 needs -- "A player chooses which half of a split card they are
  -- casting before putting it onto the stack" -- and it is carried here rather
  -- than derived at the cast, because a bare object id would present a split
  -- card's two halves as one indistinguishable option and leave the engine to
  -- pick. Same shape and same reason as Action.Cast.
  CastWhileSearching :: Decider.Decider -> PlayerId.PlayerId -> [(ObjectId.ObjectId, CardName.CardName)] -> Prompt (Maybe (ObjectId.ObjectId, CardName.CardName))
  -- | CR 601.2b: choose the value of X while casting a spell -- or, through CR
  -- 602.2b, while activating an ability, which is the same rule reached by "the
  -- remainder of the process for activating an ability is identical to the
  -- process for casting a spell listed in rules 601.2b-i". The ObjectId is
  -- whichever object is on the stack: the spell, or the ability object
  -- (Activate.activateAbility, #544).
  --
  -- The Natural is the greatest value this player could actually PAY for right now,
  -- climbed by Cast.affordableX / Activate.affordableX from the same predicate
  -- their own gates asked at CR 601.2b's X=0 floor. The two measure different costs
  -- (#90), so the bound is the greatest payable X of the cost that will really be
  -- paid.
  --
  -- ADVISORY, not a limit and not a clamp: the answer is filtered against it
  -- nowhere. CR 601.2b lets the player announce the value freely, and an
  -- announcement the cost cannot pay is answered by CR 601.2 / 602.2's reversal,
  -- which is pawl's no-op minus the prompts (#741). Both callers take that reversal
  -- at THIS step rather than carrying an already lost spell to CR 601.2h. What the
  -- bound adds is the INFORMATION a player at a table has and an answerer, seeing
  -- only this payload, did not (#417).
  --
  -- Counts LIFE, not only mana: Cost.canPay measures CR 601.2b's nonhybrid
  -- resolutions, so a Phyrexian symbol's 2 life (CR 107.4f) is one route the climb
  -- can find. It inherits that predicate's caveats, notably #365. Measured before
  -- this cost's Phyrexian symbols are announced, which is CR 601.2b's own order.
  --
  -- A bare Natural rather than a Maybe: the prompt is issued only for a cost that
  -- already passed the X=0 floor, so a greatest payable X always exists and 0 is a
  -- real answer. There is no unbounded case -- a player's mana is finite.
  --
  -- Prompted before targets (CR 601.2b precedes 601.2c), and only when the cost
  -- contains a Variable symbol.
  ChooseX :: Decider.Decider -> PlayerId.PlayerId -> ObjectId.ObjectId -> Natural.Natural -> Prompt Natural.Natural
  -- | Rule 702.42a: whether this player uses the entwine ability of the modal spell
  -- they are casting. The ObjectId is the spell; the Cost is the additional cost
  -- entwining adds on top of whichever candidate cost is then announced (CR 601.2f).
  --
  -- One question rather than two, that rule being one sentence: the widened mode
  -- choice and the intention to pay an additional cost are the same decision, so
  -- this is asked BEFORE ChooseModes, which then has nothing left to ask.
  --
  -- Asked only when entwining is available -- the spell has the keyword, every mode
  -- is legal (CR 700.2a), and some candidate cost plus this one is payable.
  ChooseEntwine :: Decider.Decider -> PlayerId.PlayerId -> ObjectId.ObjectId -> Cost.Cost Keyword.Keyword -> Prompt EntwineDecision.EntwineDecision
  -- CR 903.9a: this player's commander is in a graveyard or in exile, having
  -- arrived since the last state-based action check. Rule 903.9a is a "may", so
  -- the owner is asked; the object stays where it is if they decline, and is not
  -- asked again until it moves there afresh.
  --
  -- The OWNER is the player asked, never the controller: rule 903.9a says "its
  -- owner may put it into the command zone", and a commander that died under a
  -- thief's control is still its owner's to reclaim.
  ReturnCommander :: Decider.Decider -> PlayerId.PlayerId -> ObjectId.ObjectId -> Prompt CommandZoneDecision.CommandZoneDecision
  -- | CR 401.2: which END of a library a card an effect is putting there arrives
  -- at, when the effect leaves the choice open -- Aetherspouts' "its owner puts
  -- it on their choice of the top or bottom of their library". The ObjectId is
  -- the card being placed, read PRE-MOVE, so two creatures put two
  -- distinguishable questions on the wire (#61's requirement, met at birth).
  --
  -- The OWNER is the player asked, as ReturnCommander's is and for the same kind
  -- of reason: the card says "its owner", and CR 400.3 sends it to that owner's
  -- library whoever controlled it. NOT CR 608.2f's resolving controller.
  --
  -- Never elided: the two ends are plainly different boards. The case not asked
  -- is a STATED end (Pawl.Types.LibraryPlacement.Stated), where the rules leave
  -- nothing to ask. Asked in the sweep's APNAP order (CR 101.4, CR 608.2f's
  -- primary determination), which is what WotC's Aetherspouts ruling spells out.
  ChooseLibraryEnd :: Decider.Decider -> PlayerId.PlayerId -> ObjectId.ObjectId -> Prompt LibraryPosition.LibraryPosition
  -- | CR 401.4: "If an effect puts two or more cards in a specific position in a
  -- library at the same time, the owner of those cards may arrange them in any
  -- order." The PlayerId is that owner -- which for a library destination is also
  -- the library's owner (CR 400.3) -- the LibraryPosition is the end they are
  -- arriving at, and the [ObjectId] is the batch in the engine's canonical (sweep)
  -- order. The answer is a permutation of the entry INDICES, read as the order
  -- the cards END UP in from that end inward.
  --
  -- The end is on the wire because the answer's meaning depends on it: a player
  -- asked to order two cards has to know which end they are being stacked from.
  --
  -- A DIFFERENT decider from CR 608.2f's secondary sentence, which hands the
  -- relative order of same-controller actions to the resolving spell's
  -- controller. For a library destination CR 401.4 takes that back and gives it
  -- to the cards' owner; Aetherspouts' own ruling quotes it.
  --
  -- Asked only for a batch of two or more, which is CR 401.4's own wording rather
  -- than an elision this engine invented. Still asked when the cards are copies
  -- of one printing, OrderTriggers' posture: they are distinct objects.
  ArrangeLibraryArrivals :: Decider.Decider -> PlayerId.PlayerId -> LibraryPosition.LibraryPosition -> [ObjectId.ObjectId] -> Prompt [Natural.Natural]
  -- | CR 601.2b / 700.2a: choose the mode(s) while casting (the ObjectId is the
  -- spell). The Set ModeIndex is the LEGAL modes -- the engine pre-filters to modes
  -- whose targets are all fillable (CR 700.2a). The ModeSelection is the printed
  -- instruction being satisfied: how many modes to choose, and whether CR 700.2d
  -- lets the same one be chosen more than once.
  --
  -- The answer is a Seq and not a Set, because that instruction's exception makes
  -- a mode nameable twice; the engine rejects an answer with a repeat under the
  -- ordinary instruction, and sorts the answer either way (CR 608.2c).
  --
  -- The whole selection rather than a bare count, because the count alone cannot
  -- say how many answers there are -- the answerer needs the exception to know
  -- that one legal mode can still satisfy "choose three".
  --
  -- Prompted before X and targets, and ONLY when there is a real choice to make: a
  -- forced selection is not asked, which is every entwined cast, where CR 702.42a's
  -- "all modes" leaves no subset to pick.
  ChooseModes :: Decider.Decider -> PlayerId.PlayerId -> ObjectId.ObjectId -> Set.Set ModeIndex.ModeIndex -> ModeSelection.ModeSelection -> Prompt (Seq.Seq ModeIndex.ModeIndex)
  -- | CR 707.5 / 614.1c / 614.12a: as an object enters AS A COPY, its controller
  -- chooses which permanent to copy. The ObjectId is the entering object; the
  -- [ObjectId] is the legal copy targets, pre-filtered by the engine; Nothing is
  -- the card's own "may" decline, after which it enters as itself. Answered inside the zone change (CR 614.12a) before
  -- the enters event is recorded, so the choice really is made as the object
  -- enters. The legal set excludes anything entering in the same batch, a sibling
  -- not yet being "on the battlefield" when the choice is made.
  ChooseCopyTarget :: Decider.Decider -> PlayerId.PlayerId -> ObjectId.ObjectId -> [ObjectId.ObjectId] -> Prompt (Maybe ObjectId.ObjectId)
  -- | CR 208.2b / 614.1c: as an object enters, its controller chooses among the
  -- shapes an "as this creature enters, it becomes your choice of ..." ability
  -- offers (Primal Plasma). The ObjectId is the entering object; the answer is an
  -- index into the offered list.
  --
  -- The chosen shape is written into the object's COPIABLE snapshot (CR 707.2), so
  -- a later Clone copies the choice without any further machinery -- and then, if
  -- it copied the ABILITY too, makes its own choice on top (CR 616.2).
  --
  -- Asked only when two or more options are offered; one option is not a choice.
  ChooseEntryOption :: Decider.Decider -> PlayerId.PlayerId -> ObjectId.ObjectId -> [EntryOption.EntryOption] -> Prompt Natural.Natural
  -- | CR 702.136a / 614.1c: as a permanent with riot enters, its controller
  -- decides whether to have it enter with an additional +1/+1 counter; if they
  -- don't, it gains haste. The ObjectId is the entering object.
  --
  -- An OptionalDecision and not a two-option list, because rule 702.136a states
  -- it as a "may" with a stated consequence for declining rather than as a menu.
  -- Exercises is the counter and Declines is the haste, which is the rule's own
  -- reading order.
  --
  -- NEVER ELIDED. The two outcomes are as distinguishable as outcomes get -- a
  -- 3/3 that cannot attack this turn against a 2/2 that can -- so there is no
  -- indistinguishable-options case here, unlike ChooseEntryOption's single-option
  -- one. Pawl.Engine.Event's arm has an unreachable no-controller fallback beside
  -- it, the same shape ChooseEntryOption's carries; see there.
  ChooseRiot :: Decider.Decider -> PlayerId.PlayerId -> ObjectId.ObjectId -> Prompt OptionalDecision.OptionalDecision
  -- | CR 702.98a / 614.1c: as a permanent with unleash enters, its controller
  -- decides whether to have it enter with an additional +1/+1 counter. The
  -- ObjectId is the entering object.
  --
  -- An OptionalDecision for ChooseRiot's reason, and DISTINCT from it for
  -- ChoosePayLifeOnEntry's: a transcript that answered one as-enters "may" must
  -- not silently answer a different one. Exercises takes the counter.
  --
  -- NEVER ELIDED. Declining leaves a creature that can block where taking the
  -- counter leaves a bigger one that cannot, which is the whole trade rule
  -- 702.98a prints.
  ChooseUnleash :: Decider.Decider -> PlayerId.PlayerId -> ObjectId.ObjectId -> Prompt OptionalDecision.OptionalDecision
  -- | CR 614.1c with CR 119.4: as a permanent whose text reads "As [this
  -- permanent] enters, you may pay N life. If you don't, it enters tapped"
  -- enters, its controller decides whether to pay (Razorgrass Field). The
  -- ObjectId is the entering object and the Natural is the amount of life, which
  -- is card text rather than a rule's.
  --
  -- An OptionalDecision for ChooseRiot's reason: the card states a "may" with a
  -- stated consequence for declining, not a menu. Exercises pays and enters
  -- untapped; Declines enters tapped.
  --
  -- ELIDED IN EXACTLY ONE CASE, and it is a forced selection rather than an
  -- elision of distinguishable options: CR 119.4 lets a player pay N life only
  -- if their life total is at least N, so below that the only legal answer is to
  -- decline and Pawl.Engine.Event never asks. CR 119.4b's always-payable 0 makes
  -- a zero amount payable at any total, so that case is still asked -- and a card
  -- printing "you may pay 0 life" would be offering a real choice, since paying
  -- is what keeps the permanent untapped.
  ChoosePayLifeOnEntry :: Decider.Decider -> PlayerId.PlayerId -> ObjectId.ObjectId -> Natural.Natural -> Prompt OptionalDecision.OptionalDecision
  -- | CR 614.1c: as an object enters, its controller chooses a colour
  -- ("As this creature enters, choose a color" -- Painter's Servant). The
  -- ObjectId is the entering object.
  --
  -- No candidate list: CR 105.1 fixes the five colours and no card in the pool
  -- narrows them. Asked whenever the entering object has a controller to ask --
  -- five colours are five distinguishable options, so there is no one-option
  -- case to elide. Replacement's arm has an unreachable no-controller fallback
  -- beside it; see there.
  ChooseColor :: Decider.Decider -> PlayerId.PlayerId -> ObjectId.ObjectId -> Prompt Color.Color
  -- | CR 201.4 / 614.1c: as an object enters, a player chooses a card name ("you
  -- and an opponent each choose a card name other than a basic land card name"
  -- -- Null Chamber). The PlayerId is the CHOOSER, who is the entering object's
  -- controller for one of Null Chamber's two asks and an opponent for the other;
  -- the ObjectId is the entering object.
  --
  -- The one as-enters choice prompt whose chooser is not always the entering
  -- object's controller, which is why the two are not assumed equal anywhere
  -- this is raised. Pawl.Engine.Replacement asks in CR 101.4's APNAP order,
  -- since both choices are made at the same time.
  --
  -- No candidate list, for ChooseCreatureTypeSwap's reason carried further: CR
  -- 205.3m's creature types run to hundreds, and CR 201.4's "the name of a card
  -- in the Oracle card reference" is not a set the engine holds at all. Nothing
  -- in the layering forbids that -- Pawl.Registry sits ahead of the engine in
  -- the table, so the edge would be legal -- but it is not wired, and wiring it
  -- would hand the closed half a card-by-name lookup, which is the capability
  -- design.md §1's invariant is enforced by withholding (see
  -- Pawl.Engine.Card's header). #663 is that whole question.
  --
  -- The Filter is CR 201.4a's restriction, read off the card that asks: "the
  -- player must choose the name of a card whose Oracle text matches those
  -- characteristics", which for Null Chamber is "other than a basic land card
  -- name". ADVISORY, like ChooseX's bound -- the answer is filtered against it
  -- nowhere (#663), and for the same reason there is no candidate list.
  ChooseCardName :: Decider.Decider -> PlayerId.PlayerId -> ObjectId.ObjectId -> Filter.Filter Keyword.Keyword -> Prompt CardName.CardName
  -- | Which opponent an as-enters choice names -- Null Chamber's "you and AN
  -- OPPONENT each choose a card name". The PlayerId is the chooser, the ObjectId
  -- is the entering object, and the NonEmpty is that player's opponents. CR
  -- 614.12a is what puts the ask before the permanent enters: "If a replacement
  -- effect that modifies how a permanent enters the battlefield requires a
  -- choice, that choice is made before the permanent enters the battlefield."
  --
  -- Its own prompt rather than a reuse of ChooseDefender, which also answers with
  -- an opponent: that prompt asks CR 507.1's question, whom to attack, and a
  -- responder that knows which prompt it is answering knows which question it was
  -- asked.
  --
  -- WHO is asked is pawl's reading rather than a rule's: the card leaves "an
  -- opponent" open and no rule assigns the pick, so it goes to the ability's
  -- controller -- CR 109.5's "you", the player the card's other half already
  -- names. Asked only when there are two or more: CR 102.2's two-player game
  -- leaves exactly one opponent and nothing to ask.
  ChooseOpponent :: Decider.Decider -> PlayerId.PlayerId -> ObjectId.ObjectId -> NonEmpty.NonEmpty PlayerId.PlayerId -> Prompt PlayerId.PlayerId
  -- | CR 310.8a: which player protects a battle. The PlayerId is the chooser --
  -- CR 310.8a assigns it to the battle's controller, so this one is the rule's
  -- and not pawl's reading, unlike ChooseOpponent above. The ObjectId is the
  -- battle, and the NonEmpty is Pawl.Engine.Battle.protectorCandidates: for a
  -- Siege, CR 310.11a's opponents of its controller.
  --
  -- Asked from TWO places, which is why it carries the battle rather than
  -- assuming an entry. CR 310.8a asks as the battle enters, through the CR 614.12a
  -- as-enters route (EntryRewrite.ChooseProtector); CR 310.10 -- listed as CR
  -- 704.5w and CR 704.5x -- asks again as a state-based action when the
  -- designation has become illegal, on a battle that has been on the battlefield
  -- for turns.
  --
  -- Its own prompt rather than a reuse of ChooseOpponent, by that arm's own
  -- argument: a responder that knows which prompt it is answering knows which
  -- question it was asked, and "who protects this battle" is not "which opponent
  -- does this card's text name". Reusing it would also be wrong on candidates --
  -- a battle with no battle types takes its own controller (CR 310.8a), whom
  -- ChooseOpponent by construction never offers.
  --
  -- Asked only when there are two or more candidates, the elision ChooseDefender
  -- and ChooseCardNames both take: one candidate is one outcome, so the options
  -- are indistinguishable and there is nothing to decide. CR 102.2's two-player
  -- game leaves a Siege exactly one legal protector, so the ask is a multiplayer
  -- one in practice -- which is what makes Pawl.BattleSpec's protector cases
  -- three-seated.
  ChooseProtector :: Decider.Decider -> PlayerId.PlayerId -> ObjectId.ObjectId -> NonEmpty.NonEmpty PlayerId.PlayerId -> Prompt PlayerId.PlayerId
  -- | CR 603.3b: each player, in APNAP order, puts the triggered abilities they
  -- control on the stack in any order they choose. The [TriggerEntry] is that
  -- player's pending triggers in the engine's canonical order; the answer is a
  -- permutation of the entry INDICES giving the order they are put on the stack, so
  -- the last named resolves first.
  --
  -- A TriggerSource rather than an ObjectId inside the entry because the inherent
  -- abilities (CR 725.2's monarch pair, CR 702.179d's speed increase) have no
  -- source and are ordinary triggered abilities otherwise, so they are in this
  -- batch with no id to put on the wire.
  --
  -- Positional, but no longer positional BY NECESSITY: the entry carries the
  -- ability alongside the source (#61), so two entries DIFFER exactly when they
  -- are distinguishable. A source with two DISTINCT abilities triggered by one
  -- event is real and in the pool, and the two entries differ; two triggers of the
  -- SAME ability stay equal, which is the other half of the requirement. The
  -- converse does not hold -- equal entries can still be distinguishable -- which
  -- is what the next paragraph is about.
  --
  -- Asked ONLY when the player controls two or more AND the order is observable.
  -- Equal entries are not on their own enough to elide: they are equal up to
  -- their bindings, and CR 117.3b makes which of two same-ability triggers
  -- resolved first visible whenever the payload reads one (Aether Flash on two
  -- entrants). Pawl.Engine.Engine.orderInert is the other half, and carries the
  -- account.
  --
  -- Asked ONCE PER PASS of CR 603.3b's two-part process, not once per batch: the
  -- rule gives the own-order choice inside each pass, so a player controlling one
  -- trigger of each class is asked nothing at all. The entries offered are
  -- therefore always all of one class.
  OrderTriggers :: Decider.Decider -> PlayerId.PlayerId -> [TriggerEntry.TriggerEntry] -> Prompt [Natural.Natural]
  -- | CR 615.7: with damage from two or more applicable sources at once, the
  -- shielded player or the permanent's controller chooses which damage the shield
  -- prevents. The [DamageEvent] is those simultaneous events in the engine's
  -- canonical order; the answer is a permutation of their INDICES, giving the order
  -- the shields are offered them.
  --
  -- An ORDER rather than a pick, which is the rule read closely: within one event a
  -- shield covers as much as it can and no more, then moves on with whatever is
  -- left, so the only freedom the rule grants is WHICH event is covered first.
  --
  -- The whole DamageEvent is on the wire rather than just each source: the amounts
  -- are what the answer turns on, and the riders decide what surviving damage does.
  --
  -- Asked only when the order is observable -- two or more events one shield
  -- admits, and a remaining amount neither 0 nor enough to cover all of them.
  OrderDamage :: Decider.Decider -> PlayerId.PlayerId -> [DamageEvent.DamageEvent] -> Prompt [Natural.Natural]
  -- | CR 616.1: with two or more applicable replacement or prevention effects in
  -- the highest non-empty bucket, the affected object's controller (or its owner,
  -- or the affected player) chooses which to apply NEXT -- and then the process
  -- repeats over what is applicable now (616.1f), so this is asked once per
  -- iteration, not once per event. The [ReplacementEntry] is the candidates in the
  -- engine's canonical order (battlefield ascending, then the floating store); the
  -- answer is an index into it.
  --
  -- A PICK and not a permutation, which is where this parts company with
  -- OrderTriggers: CR 616.1 chooses one to apply and CR 616.1f re-collects, so the
  -- rest of the order is never settled here.
  --
  -- Positional, but no longer positional BY NECESSITY: the entry carries the
  -- effect alongside its source (#74), so two entries are equal exactly when they
  -- are interchangeable. Coldsteel Heart's "enters tapped" beside its "as this
  -- enters, choose a color" is one source with two applicable entry replacements
  -- in one bucket, and the two entries differ.
  --
  -- Asked only when the bucket holds two or more candidates that are not all
  -- indistinguishable: among indistinguishable ones every order yields the same
  -- board, each still getting its own CR 614.5 opportunity. Indistinguishable is
  -- equal in the EFFECT, plus -- where application reads the applying candidate,
  -- which is Replacement.readsApplier's question -- equal in CR 109.5's "you".
  ChooseReplacement :: Decider.Decider -> PlayerId.PlayerId -> [ReplacementEntry.ReplacementEntry] -> Prompt Natural.Natural
  -- | CR 603.7c: which of several minted tokens a Create's slot binds -- the "it" a
  -- delayed triggered ability armed in the same resolution will name. The ObjectId
  -- is the effect's source; the NonEmpty is the tokens actually minted, in
  -- creation order.
  --
  -- Reachable only through a replacement: a Create whose printed quantity is
  -- anything but exactly one binds every token it minted instead and asks
  -- nothing (Resolve.namesEveryToken), so the singular "it" starts with a single
  -- candidate -- and CR 614.16 scales the count at RUNTIME, giving it several.
  --
  -- CR 707.10e is the codified analogue and what settles this as a CHOICE rather
  -- than a rule the engine may apply itself: where a replacement causes a copy to
  -- target more than one object, its controller chooses one. Binding the first
  -- minted token would be the engine choosing.
  --
  -- No SlotName in the payload: the candidates are distinct minted objects, so
  -- two slot-binding Creates in one resolution already ask distinguishable
  -- questions, and the slot name is card-data vocabulary rather than anything a
  -- player sees.
  --
  -- Asked ONLY when two or more tokens were minted. One token is the whole
  -- candidate set, and where the rules leave nothing to ask, don't prompt.
  ChooseBoundToken :: Decider.Decider -> PlayerId.PlayerId -> ObjectId.ObjectId -> NonEmpty.NonEmpty ObjectId.ObjectId -> Prompt ObjectId.ObjectId
  -- | CR 701.21a: which permanents to sacrifice to pay a cost. The ObjectId is the
  -- spell being cast or the permanent whose ability is being activated; the
  -- [ObjectId] is the payer's permanents matching the component's criterion (the
  -- engine pre-filters, in ascending order); the Natural is how many. The answer
  -- is a Set because one permanent cannot be sacrificed twice for one payment.
  --
  -- Deliberately NOT Prompt.ChooseTargets or the TargetSpec machinery: CR 115.1
  -- makes a target only what the word "target" names, and conflating the two
  -- would let shroud, hexproof and "becomes the target" triggers observe a
  -- sacrifice choice. Its shape mirrors ChooseDiscard (candidates plus a count).
  --
  -- Asked ONLY when there is a choice -- more candidates than the count. Exactly
  -- as many as the count is forced, and where the rules leave nothing to ask,
  -- don't prompt.
  --
  -- Issued once per component and carries no record of what an earlier component
  -- already consumed, so two Sacrifice components of one cost each see the full
  -- candidate list (#112).
  ChooseSacrifices :: Decider.Decider -> PlayerId.PlayerId -> ObjectId.ObjectId -> [ObjectId.ObjectId] -> Natural.Natural -> Prompt (Set.Set ObjectId.ObjectId)
  -- | CR 406.2: which cards to exile from the paying player's own graveyard to
  -- pay a cost -- Headless Skaab's "exile a creature card from your graveyard".
  -- The ObjectId is the spell being cast or the permanent whose ability is being
  -- activated; the [ObjectId] is the payer's graveyard cards matching the
  -- component's criterion (the engine pre-filters, in graveyard order); the
  -- Natural is how many.
  --
  -- ChooseSacrifices' shape and posture in every respect, including its Set
  -- answer (one card cannot be exiled twice for one payment), its CR 115.1
  -- argument for not being a target choice, and its elision -- asked ONLY when
  -- there are more candidates than the count.
  --
  -- A SEPARATE arm and not ChooseSacrifices reused, even though the payloads
  -- agree: Pawl.Types.Response gives every prompt its own constructor so a
  -- decode can reject a response that does not match the prompt asked, and the
  -- two questions differ in what the candidates ARE -- permanents on the
  -- battlefield against cards in a graveyard.
  ChooseExilesFromGraveyard :: Decider.Decider -> PlayerId.PlayerId -> ObjectId.ObjectId -> [ObjectId.ObjectId] -> Natural.Natural -> Prompt (Set.Set ObjectId.ObjectId)
  -- | CR 614.1c with CR 614.13a: sacrifice ANY NUMBER of the candidates as this
  -- permanent enters, which is a different question from ChooseSacrifices above
  -- and not expressible as it -- that one names how many and Pawl.Engine.Cost
  -- rejects an answer of any other size, while this one admits every subset
  -- including the empty one. Shimatsu the Bloodcloaked's "As this creature
  -- enters, sacrifice any number of permanents."
  --
  -- No count field, because there is no count: the offer IS the candidate list.
  --
  -- ASKED EVEN AT ONE CANDIDATE, unlike ChooseSacrifices' elision: with a free
  -- choice of subset, one candidate still leaves two distinguishable answers
  -- (sacrifice it or not), so eliding would decide for the player. Asked even at
  -- ZERO candidates would not -- the empty set is the only answer -- so the
  -- caller skips the prompt there.
  --
  -- Answers as Response.ChoseSacrifices: the payload is the same set of
  -- permanents, and a transcript that replays one replays the other.
  ChooseAnyNumberToSacrifice :: Decider.Decider -> PlayerId.PlayerId -> ObjectId.ObjectId -> [ObjectId.ObjectId] -> Prompt (Set.Set ObjectId.ObjectId)
  -- | CR 702.122a: which permanents to TAP to pay a cost whose payment is
  -- measured by their TOTAL POWER. The ObjectId is the permanent whose ability
  -- is being activated (the Vehicle); the [ObjectId] is the payer's untapped
  -- permanents matching the component's criterion, engine-pre-filtered in
  -- ascending order; the Natural is the threshold the chosen set's summed power
  -- must reach.
  --
  -- Neither of the two sacrifice prompts above, and not expressible as either.
  -- ChooseSacrifices names how many objects; this one does not, because CR
  -- 702.122a's cost never does -- crew 6 is paid by one 7-power creature or by
  -- four 2-power ones. ChooseAnyNumberToSacrifice names no count either, but
  -- admits every subset including the empty one, and here the empty set pays
  -- nothing unless the threshold is 0. So the count field carries a THRESHOLD
  -- rather than a size, and Pawl.Engine.Cost validates against a sum.
  --
  -- ASKED WHENEVER THE COST IS PAID, with no elision, which is the one place
  -- this differs from every sibling: whether the answer is forced is a question
  -- about SUBSETS -- crew 6 with a 6-power and a 7-power creature has two legal
  -- answers, crew 6 with a 4 and a 3 has one -- and deciding it means
  -- enumerating them. Asking a forced question costs a redundant prompt; not
  -- asking an unforced one decides for the player, which the engine may never
  -- do.
  --
  -- A Set, for ChooseSacrifices' reason: one permanent cannot be tapped twice
  -- for one payment. Answers as Response.ChoseTaps, which is its own
  -- constructor rather than a reuse of ChoseSacrifices -- a transcript that
  -- taps creatures and one that sacrifices them are not the same transcript.
  ChooseTapsForTotalPower :: Decider.Decider -> PlayerId.PlayerId -> ObjectId.ObjectId -> [ObjectId.ObjectId] -> Natural.Natural -> Prompt (Set.Set ObjectId.ObjectId)
  -- | CR 701.3a: where an effect that moves an already-attached permanent puts it.
  -- The first ObjectId is the permanent being moved (Crown of the Ages' targeted
  -- Aura); the NonEmpty is the destinations its card text admits.
  --
  -- CHOOSE, not target: such an effect targets the Aura and not either creature, so
  -- a destination is offered whoever's it is and whether or not it can be targeted,
  -- and nothing is re-checked under CR 608.2b. The offer is the card's TEXT and
  -- nothing more -- "another creature" gets every creature, including ones CR
  -- 303.4j will refuse to move the Aura onto, since narrowing past what the card
  -- says would answer that rule on the player's behalf; "another permanent it can
  -- enchant" gets only the legal ones (Filter.CanHostSubject).
  --
  -- Elided at exactly one candidate: the effect is mandatory, so a single
  -- destination leaves nothing to decide -- unlike ChooseManaSource, where
  -- declining is always an answer. The current host
  -- is never among the candidates (CR 701.3b), so it is not being withheld.
  --
  -- NonEmpty rather than []: the caller does not raise this when no destination
  -- exists, and a fallback must be total.
  ChooseAttachment :: Decider.Decider -> PlayerId.PlayerId -> ObjectId.ObjectId -> NonEmpty.NonEmpty ObjectId.ObjectId -> Prompt ObjectId.ObjectId
  -- | CR 303.4k with CR 614.1e: whether an Aura being turned face up exercises its
  -- printed "you MAY attach it" (Gift of Doom). The ObjectId is the Aura turning
  -- over, and CR 303.4k names the player -- "the Aura's controller".
  --
  -- An OptionalDecision and a prompt of its own rather than a decline arm on
  -- ChooseAttachment beside it, because the two questions are asked by different
  -- authorities and a transcript must tell their answers apart: the "may" is the
  -- CARD's, and WHICH host is rule 303.4k's own "they MUST choose a legal object
  -- or player". ChooseAttachment then does its ordinary job, elision and all.
  -- ChooseRiot and ChoosePayLifeOnEntry are the shape this follows -- a card
  -- stating a "may" inside a replacement effect, one arm per question.
  --
  -- Not ChooseOptional, which is CR 603.5's printed "may" over a MODE of a
  -- resolving spell or ability. Turning a permanent face up is a special action
  -- (CR 116.2b) and nothing is resolving, so there is no stack object to carry
  -- and no ModeIndex to index.
  --
  -- NEVER ELIDED where it is asked at all. Declining leaves the Aura attached to
  -- nothing, and CR 704.5m puts an unattached Aura into its owner's graveyard --
  -- so the two answers reach a board with the permanent and a board without it.
  -- Pawl.Engine.Event does not ask when the rule leaves nothing to decide: with
  -- no legal host the "may" has no exercisable side.
  ChooseTurnUpAttachment :: Decider.Decider -> PlayerId.PlayerId -> ObjectId.ObjectId -> Prompt OptionalDecision.OptionalDecision
  -- | CR 601.2b: the player announces their intention to pay any alternative or
  -- additional costs. Issued after the modes and before X and targets, at that
  -- rule's own position. The [Cost] is the PAYABLE candidates, pre-filtered through
  -- Cost.costsFor, total and canPay at the CR 601.2b X=0 floor.
  --
  -- CR 118.9b makes an alternative cost optional, so a player who can afford both
  -- is genuinely choosing. Asked only when two or more candidates are payable.
  ChooseCost :: Decider.Decider -> PlayerId.PlayerId -> ObjectId.ObjectId -> [Cost.Cost Keyword.Keyword] -> Prompt (Cost.Cost Keyword.Keyword)
  -- | CR 103.5: whether this player takes a mulligan. The MulliganOffer carries
  -- both halves of what a player at a table can see -- how many mulligans they
  -- have already taken, and how many cards taking another would bottom. Those
  -- diverge under CR 103.5c's free first mulligan, which is why the payload is
  -- not the raw count it used to be (#176).
  --
  -- Asked in turn order, once per round, only while the player's current hand is
  -- > 0 cards (CR 103.5 final sentence: no mulligans past a zero-card hand). A
  -- player who has kept is never asked again (CR 103.5: keeping is terminal).
  -- Carries a Decider like every other player-facing prompt; at game setup
  -- activeControl is Nothing, so it is the player themselves (CR 723 satisfied
  -- for free).
  DeclareMulligan :: Decider.Decider -> PlayerId.PlayerId -> MulliganOffer.MulliganOffer -> Prompt MulliganDecision.MulliganDecision
  -- | CR 103.5: after redrawing, put `count` cards from `hand` on the bottom of the
  -- library, in the player's chosen order. The [ObjectId] is the redrawn hand;
  -- the answer is an ordered list of exactly `count` of those ids (first-listed
  -- ends up higher in the library, drawn sooner). Bottom order IS future draw
  -- order, so it is a real choice even when the subset is forced (count == hand
  -- size), which is why the answer is an ordered list, never a Set. Asked only
  -- when the hand has >= 2 cards; with 0 or 1 there is one possible outcome, and
  -- where the rules leave nothing to ask, don't prompt.
  Bottom :: Decider.Decider -> PlayerId.PlayerId -> [ObjectId.ObjectId] -> Natural.Natural -> Prompt [ObjectId.ObjectId]
  -- | CR 103.5b: an action a card lets a player take "any time they could
  -- mulligan". Each entry is one action a card in hand grants -- the card, and
  -- WHICH of its actions (Pawl.Types.HandActionIndex), since a face may print
  -- more than one and the two are different offers. The answer is which to take,
  -- or Nothing to decline.
  --
  -- Offered immediately BEFORE each DeclareMulligan and again after each action
  -- taken -- that rule makes the declaration follow, and nothing in it limits a
  -- player to one action. Offered in every round, not just the first, and only to a
  -- player who has not yet kept.
  --
  -- Performing the action is NOT taking a mulligan: nothing is shuffled or
  -- bottomed, so it feeds neither the bottom count nor CR 103.5c's free allowance.
  --
  -- Not asked when the list is empty.
  MulliganAction :: Decider.Decider -> PlayerId.PlayerId -> [(ObjectId.ObjectId, HandActionIndex.HandActionIndex)] -> Prompt (Maybe (ObjectId.ObjectId, HandActionIndex.HandActionIndex))
  -- | CR 103.6 / 103.6a: an action a card in this player's opening hand lets them
  -- take once the mulligan process is complete. The entries are shaped exactly as
  -- MulliganAction's -- the card and which of its actions; the answer is which to
  -- take, or Nothing to decline.
  --
  -- Offered in turn order, starting player first, and repeatedly to the same player
  -- until they decline: CR 103.6 lets them take any such actions in any order.
  --
  -- A SEPARATE channel from MulliganAction rather than a reuse: that window sits AT
  -- a mulligan declaration and this one opens once the process is complete, so an
  -- interpreter that could not tell them apart could not answer either well.
  OpeningHandAction :: Decider.Decider -> PlayerId.PlayerId -> [(ObjectId.ObjectId, HandActionIndex.HandActionIndex)] -> Prompt (Maybe (ObjectId.ObjectId, HandActionIndex.HandActionIndex))
  -- | CR 603.5 / 608.2d: whether the controller of a resolving spell or ability
  -- exercises a printed "may". The ObjectId is the object RESOLVING (the spell,
  -- or the ability object on the stack -- not its source, since two triggers off
  -- one source resolve as two distinct stack objects); the ModeIndex is which of
  -- its chosen modes is asking, so a modal payload with two optional modes puts
  -- two DISTINGUISHABLE questions on the wire -- the discriminator OrderTriggers
  -- gained with its TriggerEntry (#61) and ChooseReplacement with its
  -- ReplacementEntry (#74).
  --
  -- CR 603.5 makes this a resolution-time prompt rather than a cast-time one: an
  -- optional ability goes on the stack regardless, and the choice is made when it
  -- resolves. CR 608.2d then places it exactly.
  --
  -- NEVER elided. "You may gain 2 life" is a genuine choice even when it looks
  -- strictly good: a life total is read by other cards, so both answers are
  -- distinguishable game states. The one case where it is not asked is where
  -- nothing is being decided -- an ability whose targets are all illegal is removed
  -- from the stack by CR 608.2b first. That covers every optional card in the pool,
  -- all single-mode; a modal payload mixing a live mode with a dead optional one
  -- would reach this prompt with nothing to decide (#336).
  --
  -- The ModeIndex and the ClauseIndex together say which question this is: the
  -- "may" covers the CLAUSE it is printed on (CR 608.2e), not the whole mode, so
  -- a mode with two optional clauses raises two distinguishable prompts. Whether
  -- the clause's effects can accomplish anything is deliberately NOT consulted --
  -- that would make this prompt depend on which effects a clause holds, and the
  -- rules core never asks an effect's identity.
  ChooseOptional :: Decider.Decider -> PlayerId.PlayerId -> ObjectId.ObjectId -> ModeIndex.ModeIndex -> ClauseIndex.ClauseIndex -> Prompt OptionalDecision.OptionalDecision
  -- | CR 608.2g: a cast that a RESOLVING effect specifically allows -- "if an
  -- effect specifically instructs or allows a player to cast a spell during
  -- resolution, they do so by following the steps in rules 601.2a-i". CR
  -- 310.11b's "then you may cast it transformed without paying its mana cost" is
  -- the producer: Exercises casts it, Declines leaves the card where it is.
  --
  -- The ObjectId is the CARD being offered -- the exiled incarnation CR 400.7
  -- minted, not the ability resolving -- and the CardName is the half CR 712.11a
  -- puts on the stack -- the same pair CastWhileSearching carries, and the same
  -- pair Action.Cast carries alongside CR 708.4's facing, for the same reason: a
  -- bare id would leave which face is being offered invisible to the answerer.
  -- No facing here, because an OfferCast opcode offers no face-down cast (see
  -- Pawl.Engine.Resolve.offerCast).
  --
  -- Distinct from CastWhileSearching, which is the same rule's other producer.
  -- That one offers a LIST and loops, because CR 601.3's Panglacial permission
  -- ranges over a whole library and several cards may hold it; this one offers
  -- exactly the one object the resolving effect named, so the question is
  -- yes-or-no and is asked once.
  --
  -- Distinct from ChooseOptional, which is CR 603.5's printed "may" over a clause
  -- of a card's own text. CR 310.11b's "may" is not printed on any card at all --
  -- it is the rule's own offer, made mid-resolution by an ability the engine
  -- mints -- so it has no Clause to ride and no ModeIndex/ClauseIndex pair to
  -- name it.
  --
  -- NEVER elided: CR 601.2b's own decisions aside, casting and not casting reach
  -- plainly different boards. The offer is not made at all when the rules leave
  -- nothing to ask -- the card is no longer where the effect left it (CR 608.2h),
  -- or the cast is one Cast.castableWhenOffered says cannot legally happen.
  OfferedCast :: Decider.Decider -> PlayerId.PlayerId -> ObjectId.ObjectId -> CardName.CardName -> Prompt OptionalDecision.OptionalDecision
  -- | CR 118.12 / 118.12a: whether this player pays a cost a RESOLVING spell or
  -- ability offers them -- Mana Leak's "unless its controller pays {3}", which CR
  -- 118.12a rewrites as "its controller may pay {3}. If they don't, counter it."
  -- The ObjectId is the object resolving and the ModeIndex/ClauseIndex pair is
  -- which clause of which chosen mode is asking, all for Prompt.ChooseOptional's
  -- reasons; the Cost is what is being offered, which is the information the
  -- answer turns on. The "unless" scopes to its clause exactly as the "may"
  -- does, so a card whose "unless" governs only some of its instructions leaves
  -- the rest to happen either way (#703).
  --
  -- The PlayerId is emphatically NOT the resolving controller, which is what
  -- separates this from every other resolution-time prompt: CR 118.12's clause
  -- names a player, and for this card family that player is the one the effects
  -- would be aimed AT. Routed through Decide.deciderFor like every other
  -- player-facing prompt, so a player controlled under CR 723.1 has their
  -- controller answer.
  --
  -- Asked at CR 118.12's own moment, when the spell or ability RESOLVES, so a
  -- countered Mana Leak never asks -- observably different from an announcement
  -- at CR 601.2f-h, where the cost of a spell being cast is paid.
  --
  -- NEVER elided for a payable cost: CR 118.12a's rewriting makes the cost a
  -- "may", and both answers reach different boards. The one case not asked is
  -- where the rules leave nothing to ask -- CR 118.3's "a player can't pay a cost
  -- without having the necessary resources to pay it fully", which leaves
  -- declining as the only possible answer. CR 118.12's clause covers that case in
  -- as many words ("does, doesn't, or CAN'T"). Its Standstill example is NOT this
  -- one: that cost is mandatory ("sacrifice this enchantment. If you do"), so its
  -- "can't" is 118.12's "started to pay a mandatory cost" limb, which is the
  -- positive shape pawl cannot represent at all (#701).
  ChooseToPay :: Decider.Decider -> PlayerId.PlayerId -> ObjectId.ObjectId -> ModeIndex.ModeIndex -> ClauseIndex.ClauseIndex -> Cost.Cost Keyword.Keyword -> Prompt PaymentDecision.PaymentDecision
  -- | CR 601.2b: the player announces whether they intend to pay 2 life or a
  -- coloured mana cost for each Phyrexian symbol. CR 118.13a puts the choice HERE
  -- rather than at payment. The ObjectId is the spell or the permanent whose
  -- ability is being activated (CR 602.2b); the Color is the symbol's own, so two
  -- symbols of different colours put DISTINGUISHABLE questions on the wire.
  --
  -- One prompt per symbol, in printed order, and the NonEmpty is the routes
  -- actually payable given the announcements already made, so a player can never
  -- announce a route CR 118.3 will not let them complete. Payable is measured at CR
  -- 601.2f's TOTAL rather than the printed cost, which keeps that promise under a
  -- cost increase or reduction. Two symbols of the SAME colour ask two identical
  -- questions, which is sound here because the answers are interchangeable: both
  -- demand the same mana and the same 2 life, so which prompt got which is not
  -- observable -- a claim neither OrderTriggers nor ChooseReplacement could make
  -- until each entry carried the ability or effect itself (#61, #74).
  --
  -- Elided when only one route is payable -- no source of the symbol's colour, or a
  -- life total below CR 119.4's floor.
  AnnouncePhyrexianPayment :: Decider.Decider -> PlayerId.PlayerId -> ObjectId.ObjectId -> Color.Color -> NonEmpty.NonEmpty PhyrexianPayment.PhyrexianPayment -> Prompt PhyrexianPayment.PhyrexianPayment
  -- | CR 601.2b: "If a cost that will be paid as the spell is being cast includes
  -- hybrid mana symbols, the player announces the nonhybrid equivalent cost they
  -- intend to pay." CR 118.13a puts that choice HERE rather than at payment. The
  -- ObjectId is the spell or the permanent whose ability is being activated (CR
  -- 602.2b); the ManaType is the symbol's own stated type, so a {2/R} and a {2/G}
  -- in one cost put DISTINGUISHABLE questions on the wire.
  --
  -- CR 107.4e's MONOCOLORED half only ({2/R}), which is the half whose two ways
  -- spend a different NUMBER of mana. The colour/colour hybrid ({W/U}) is
  -- AnnounceHybridHalf below, and it is a separate constructor because its two
  -- ways are two mana TYPES rather than one type against an amount of generic
  -- mana, which is not a HybridPayment.
  --
  -- One prompt per symbol, in printed order, and the NonEmpty is the routes
  -- actually payable given the announcements already made -- the
  -- AnnouncePhyrexianPayment contract, for the same CR 601.2b last sentence, and
  -- payable is measured at CR 601.2f's TOTAL for the same reason. Two {2/R}s in
  -- one cost ask two identical questions, which is sound here because the answers
  -- are interchangeable: both demand the same one mana or the same {2}, so which
  -- prompt got which is not observable.
  --
  -- Elided when only one route is payable -- no source of the symbol's type, or
  -- too few mana on the board for the {2}.
  AnnounceHybridPayment :: Decider.Decider -> PlayerId.PlayerId -> ObjectId.ObjectId -> ManaType.ManaType -> NonEmpty.NonEmpty HybridPayment.HybridPayment -> Prompt HybridPayment.HybridPayment
  -- | CR 601.2b's same sentence for CR 107.4e's COLOUR/COLOUR half ({G/U}):
  -- "the player announces the nonhybrid equivalent cost they intend to pay",
  -- which for this symbol is WHICH of its two mana types the one mana will be.
  -- CR 118.13a puts that choice HERE rather than at payment. The ObjectId is
  -- the spell or the permanent whose ability is being activated (CR 602.2b);
  -- the ManaSymbol is the hybrid symbol itself, so a {G/U} and a {R/W} in one
  -- cost put DISTINGUISHABLE questions on the wire.
  --
  -- Answered with a ManaType and not with a left/right flag, the
  -- ChooseReductionHalf posture: the answer IS the nonhybrid equivalent, so
  -- nothing downstream has to re-read the symbol to learn what was announced.
  --
  -- BOTH WAYS SPEND ONE MANA, so unlike AnnounceHybridPayment above this
  -- announcement never changes CR 601.2f's total and no cost reduction turns on
  -- it. What it changes is WHICH unit of an oversupplied pool is consumed, and
  -- so what floats afterwards -- with {G}{U} in the pool a {G/U} leaves the
  -- other, and the two boards differ (Pawl.ManaSpec's Gyre Engineer case).
  --
  -- One prompt per symbol, in printed order, and the NonEmpty is the halves
  -- actually payable given the announcements already made -- the
  -- AnnouncePhyrexianPayment contract, for the same CR 601.2b last sentence.
  -- Two {G/U}s in one cost ask two identical questions, which is sound here
  -- because the answers are interchangeable: both demand one mana of the named
  -- type, so which prompt got which is not observable.
  --
  -- Elided when only one half is payable -- no source of the other type -- and
  -- for the degenerate `Hybrid t t`, whose halves are one type.
  AnnounceHybridHalf :: Decider.Decider -> PlayerId.PlayerId -> ObjectId.ObjectId -> ManaSymbol.ManaSymbol -> NonEmpty.NonEmpty ManaType.ManaType -> Prompt ManaType.ManaType
  -- | CR 118.7e: "If a cost is reduced by an amount of mana represented by a
  -- hybrid mana symbol, the player paying that cost chooses one half of that
  -- symbol at the time the cost reduction is applied (see rule 601.2f)."
  --
  -- A DIFFERENT QUESTION from AnnounceHybridPayment above, and that is why it is
  -- a different constructor rather than a reuse. That one is CR 601.2b's
  -- announcement about a symbol in the cost being PAID, made before CR 601.2f
  -- totals anything; this one is about a symbol in a REDUCTION, made as CR
  -- 601.2f applies it, and nothing about the answer constrains what the spell's
  -- own symbols may still be announced as. Sharing a constructor would also
  -- leave Pawl.Engine.Replay unable to tell a transcript's two answers apart.
  --
  -- The ManaSymbol payload is the hybrid symbol being reduced BY, so a {2/B} and
  -- a {W/U} in one player's reductions put distinguishable questions on the
  -- wire; the NonEmpty is that symbol's two halves written as CR 118.7e's own
  -- outcomes -- an OfType for "one mana of that type", a Generic for "an amount
  -- of generic mana equal to that half's number". Answering with the resulting
  -- SYMBOL rather than with a left/right flag is what lets both of CR 107.4e's
  -- shapes use one prompt: {W/U}'s halves are two types, {2/B}'s are a type and
  -- a number, and neither fits the other's payload.
  --
  -- One prompt per symbol, in the order the reductions are read. Two identical
  -- reductions ask two identical questions, which is sound because the answers
  -- are interchangeable: the pooled bag applyAdjustments cancels against does not
  -- record which prompt contributed which symbol.
  --
  -- NOT filtered by payability, unlike the two announcements above. CR 118.7e
  -- puts no such condition on the choice -- a player may take the half that
  -- reduces nothing -- and CR 601.2f's own floor is what keeps that legal.
  -- Elided only for the degenerate `Hybrid t t`, whose halves are one symbol.
  ChooseReductionHalf :: Decider.Decider -> PlayerId.PlayerId -> ObjectId.ObjectId -> ManaSymbol.ManaSymbol -> NonEmpty.NonEmpty ManaSymbol.ManaSymbol -> Prompt ManaSymbol.ManaSymbol
